### ISSUE TITLE
Error: error:24064064:random number generator:SSLEAY_RAND_BYTES:PRNG not seeded

### ISSUE THREAD

**Issue by pyrzak** [karma-runner/karma#1024]
I ran into this error when using karma. I followed the instructions here:

https://groups.google.com/forum/#!topic/angular-dart/hYY8WN_5OQc

I wasn't sure if this was a known issue or something to do with my config. I'm running karma with requirejs, mocha, and coverage. Let me know if you need more details or if this is part of another plugin.

**Comment by danielbaak** [comment]
Same issue here

```
karma start
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [launcher]: Starting browser Chrome
ERROR [karma]: [Error: error:24064064:random number generator:SSLEAY_RAND_BYTES:PRNG not seeded]
Error: error:24064064:random number generator:SSLEAY_RAND_BYTES:PRNG not seeded
  at Manager.generateId (/home/default/Projects/requirejs-tpl/node_modules/karma/node_modules/socket.io/lib/manager.js:735:12)
  at /home/default/Projects/requirejs-tpl/node_modules/karma/node_modules/socket.io/lib/manager.js:790:21
  at Manager.authorize (/home/default/Projects/requirejs-tpl/node_modules/karma/node_modules/socket.io/lib/manager.js:916:5)
  at Manager.handleHandshake (/home/default/Projects/requirejs-tpl/node_modules/karma/node_modules/socket.io/lib/manager.js:786:8)
  at Manager.handleRequest (/home/default/Projects/requirejs-tpl/node_modules/karma/node_modules/socket.io/lib/manager.js:593:12)
  at Server.<anonymous> (/home/default/Projects/requirejs-tpl/node_modules/karma/node_modules/socket.io/lib/manager.js:119:10)
  at Server.EventEmitter.emit (events.js:98:17)
  at HTTPParser.parser.onIncoming (http.js:2108:12)
  at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
  at Socket.socket.ondata (http.js:1966:22)
  at TCP.onread (net.js:525:27)
```

These are all dependencies:
```
 "devDependencies": {                                                            
           "phantomjs": "~1.9.16",                                                       
           "requirejs": "~2.1.16",                                                       
           "karma": "~0.12.31",                                                          
           "jasmine": "~2.2.1",                                                          
           "jasmine-core": "~2.2.0",                                                     
           "karma-jasmine": "~0.3.5",                                                    
           "karma-requirejs": "~0.2.2",                                                  
           "karma-phantomjs-launcher": "~0.1.4",                                         
           "karma-chrome-launcher": "~0.1.7"                                             
}    
```

Strangely enough this only happens on one project I'm working on, can't seem to figure out why.
Any ideas?

**Comment by danielbaak** [comment]
Just had the same issue ... did
```
rm -rf node_modules
npm install
```
and everything suddenly worked. (make sure your package.json contains all dependencies before doing this)

Hope this helps.

**Comment by harshayburadkar** [comment]
rm -rf node_modules
npm install

Worked for me too! Thanks!
