### ISSUE TITLE
this._browsers is undefined when calling push in lib/reporters/base.js

### ISSUE THREAD

**Issue by kstudent** [karma-runner/karma#1034]
I was following this tutorial [1] when came accross the following error message (on Step "Running JS Unit Tests" / "How to Run Tests with Karma" / Step 13):

```
ERROR [karma]: [TypeError: Cannot call method 'push' of undefined]
TypeError: Cannot call method 'push' of undefined
    at onBrowserStart (/home/chri/usr/etc/node_modules/karma/lib/reporters/base.js:14:20)
    at null.<anonymous> (/home/chri/usr/etc/node_modules/karma/lib/events.js:15:22)
    at EventEmitter.emit (events.js:117:20)
    at onStart (/home/chri/usr/etc/node_modules/karma/lib/browser.js:128:13)
    at Socket.<anonymous> (/home/chri/usr/etc/node_modules/karma/lib/events.js:15:22)
    at Socket.EventEmitter.emit [as $emit] (events.js:117:20)
    at SocketNamespace.handlePacket (/home/chri/usr/etc/node_modules/karma/node_modules/socket.io/lib/namespace.js:335:22)
    at Manager.onClientMessage (/home/chri/usr/etc/node_modules/karma/node_modules/socket.io/lib/manager.js:488:38)
    at WebSocket.Transport.onMessage (/home/chri/usr/etc/node_modules/karma/node_modules/socket.io/lib/transport.js:387:20)
    at Parser.<anonymous> (/home/chri/usr/etc/node_modules/karma/node_modules/socket.io/lib/transports/websocket/hybi-16.js:39:10)
Done.
```

Afterwards, Karma stops working, the browser client closes itself and I dont get to execute any unit tests. Placing some console log statemens implies that the trace didn't go through onRunStart (which should initialize this._browsers). The issue looks like a duplicate of [2], however I'm using Karma Version 0.12.9. 

My environment looks as follows:
- Linux 3.11.0-18-generic #32-Ubuntu SMP Tue Feb 18 21:11:14 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
- Nebeans 8.0
- Node.js v0.10.23
- Java version "1.7.0_51", Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mod)
- Chrome Version 33.0.1750.152

Since I'm totally new to Karma / TDD with Javascript, I cant really tell if karma itself or the adapter (or even netbeans) is the problem. 

Regards, Christof

[1] https://netbeans.org/kb/docs/webclient/html5-js-support.html
[2] https://github.com/mlex/karma-spec-reporter/issues/6

**Comment by helzgate** [comment]
I go this error when passing an empty [].  I changed the variable in my calling function to something like `exclude: 'some path'` and this still caused the error.  I then changed my variable to `exclude: ['some path'] and it worked
