### ISSUE TITLE
Karma does not recognize file changes

### ISSUE THREAD

**Issue by AlexCppns** [karma-runner/karma#1046]
I am getting an error on a line/column that does not exist:
```
Chrome 34.0.1847 (Mac OS X 10.9.2) contactForm processFull creates a post with the action contact_form FAILED
	TypeError: Cannot read property 'value' of undefined
	    at Object.contactForm.processFull (/app/assets/javascripts/angular_js/services/contact_form_service.js:9:5118)
	    at null.<anonymous> (/spec/javascripts/unit/services/contactform_service_spec.js:68:19)
	    at Object.invoke (/vendor/assets/javascripts/angular.js:3712:17)
	    at workFn (/spec/javascripts/lib/angular/angular-mocks.js:2149:20)
	Error: Declaration Location
	    at window.inject.angular.mock.inject (/spec/javascripts/lib/angular/angular-mocks.js:2134:25)
	    at null.<anonymous> (/spec/javascripts/unit/services/contactform_service_spec.js:65:55)
	    at null.<anonymous> (/spec/javascripts/unit/services/contactform_service_spec.js:63:3)
	    at /spec/javascripts/unit/services/contactform_service_spec.js:1:1
```

Karma version is 0.12.12
Running on MacOSX.

I tried to rename/make significant changes inside the file. Karma does pick those up but as soon as I revert it to state close to its original state it does the same error.

**Comment by Dignifiedquire** [comment]
Closing due to inactivity
