### ISSUE TITLE
Error trying to run karma programmatically

### ISSUE THREAD

**Issue by thiagopnts** [karma-runner/karma#1124]
I'm trying to run karma from my Gulpfile, the task is basically this:

```javascript
var karma = require('karma').server;
gulp.task('test', function(done) {
  karma.start({configFile: path.resolve('karma.conf.js')}, done);
});
```
My karma config file: https://gist.github.com/thiagopnts/4584193678eea0431689

When I run `gulp test` I get this error:

```
[23:36:00] Starting 'test'...
WARN [plugin]: Error during loading /Users/thiago/code/player3/node_modules/karma-traceur-preprocessor plugin:
  Reflect is not defined
[23:36:01] 'test' errored after 735 ms
[23:36:01] Error: No provider for framework:traceur! (Resolving: framework:traceur)
    at error (/Users/thiago/code/player3/node_modules/karma/node_modules/di/lib/injector.js:22:68)
    at Object.parent.get (/Users/thiago/code/player3/node_modules/karma/node_modules/di/lib/injector.js:9:13)
    at get (/Users/thiago/code/player3/node_modules/karma/node_modules/di/lib/injector.js:54:19)
    at /Users/thiago/code/player3/node_modules/karma/lib/server.js:31:14
    at Array.forEach (native)
    at start (/Users/thiago/code/player3/node_modules/karma/lib/server.js:30:21)
    at invoke (/Users/thiago/code/player3/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at Object.exports.start (/Users/thiago/code/player3/node_modules/karma/lib/server.js:306:12)
    at Gulp.<anonymous> (/Users/thiago/code/    at Gulp.<anonymous> (/Us      at Gulp.<anonymous> (/Users/thiago/code/
at Gulp.<anonymous>
at Gulp.<anonymous> (/Users/thiago/code/)
```

`$ karma start` runs just fine. I'm not sure if this is a problem of karma-traceur-preprocessor plugin, traceur-compiler or from karma itself. It occurs when the plugin tries to `require('traceur')`. Any ideas?

**Comment by Dignifiedquire** [comment]
> For questions and support please use the mailing list or Gitter.
> The issue tracker is for bug reports and feature discussions only.
