### ISSUE TITLE
npm rebuild  fails on linux box if node_modules/karma directory is copied from mac to linux

### ISSUE THREAD

**Issue by ChickenFur** [karma-runner/karma#1169]
The submodule fsevents of the chokidar submodule causes npm rebuild to fail on a linux box if node_modules/karma directory is copied from a mac box to a linux box

To Reproduce:

On a mac box

```
npm install karma 
```

Now commit your node_modules directory and push them up

```
git add --all
git commit
git push
```

clone the repo on the linux box

on the linux box run npm rebuild

```
npm rebuild
```

Console Output:

```
> fsevents@0.2.1 install /home/docusign/jenkins/workspace/Martini0_Auto_Deploy/repo/node_modules/karma/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild


module.js:340
    throw err;
          ^
Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:1
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:532:25)
    at startup (node.js:80:7)
    at node.js:902:3
Traceback (most recent call last):
  File "/usr/bin/gyp", line 18, in <module>
    sys.exit(gyp.main(sys.argv[1:]))
  File "/usr/lib/python2.6/site-packages/gyp/__init__.py", line 462, in main
    options.circular_check)
  File "/usr/lib/python2.6/site-packages/gyp/__init__.py", line 100, in Load
    depth, generator_input_info, check, circular_check)
  File "/usr/lib/python2.6/site-packages/gyp/input.py", line 2255, in Load
    depth, check)
  File "/usr/lib/python2.6/site-packages/gyp/input.py", line 388, in LoadTargetBuildFile
    build_file_path)
  File "/usr/lib/python2.6/site-packages/gyp/input.py", line 1011, in ProcessVariablesAndConditionsInDict
    build_file)
  File "/usr/lib/python2.6/site-packages/gyp/input.py", line 1026, in ProcessVariablesAndConditionsInList
    ProcessVariablesAndConditionsInDict(item, is_late, variables, build_file)
  File "/usr/lib/python2.6/site-packages/gyp/input.py", line 1011, in ProcessVariablesAndConditionsInDict
    build_file)
  File "/usr/lib/python2.6/site-packages/gyp/input.py", line 1030, in ProcessVariablesAndConditionsInList
    expanded = ExpandVariables(item, is_late, variables, build_file)
  File "/usr/lib/python2.6/site-packages/gyp/input.py", line 697, in ExpandVariables
    (contents, p.returncode))
```

A workaround is to .gitignore the node_module/karma directory.

Then run npm install as part of the deploy script.  

I can't do this because it puts a dependency on npm for deploying.

Or is there a way to change the way npm rebuild is done so it ignores the fsevents module on the linux box.

Thanks for any help or feedback!

**Comment by Dignifiedquire** [comment]
Closung due to inactivity. Please feel free to open a new issue if this problem still persists
