### ISSUE TITLE
Karma watcher is crashing when files are modified by IntelliJ

### ISSUE THREAD

**Issue by fresheneesz** [karma-runner/karma#1177]
When I run karma's watcher, when I edit a file with intelliJ, karma crashes after telling me: 

```
ERROR [karma]: { [Error: watch ENOENT] code: 'ENOENT', errno: 'ENOENT', syscall: 'watch' }
Error: watch ENOENT
    at errnoException (fs.js:1024:11)
    at FSWatcher.start (fs.js:1056:11)
    at Object.fs.watch (fs.js:1081:11)
    at EventEmitter.FSWatcher._watch (C:\<omitted>\npm\node_modules\karma\node_modules\chokidar\index.js:246:18)
    at EventEmitter.FSWatcher._handleFile (C:\<omitted>\npm\node_modules\karma\node_modules\chokidar\index.js:280:8)

    at C:\<omitted>\npm\node_modules\karma\node_modules\chokidar\index.js:356:33
    at Object.oncomplete (fs.js:107:15)
INFO [watcher]: Changed file "D:/<omitted>/karma/spec/SpecHelper.js".
```

I'm on windows 8 64 bit and karma version 0.12.23. I believe what is happening is that IntelliJ is changing the file's name, then creating a new file based on this https://github.com/karma-runner/karma/issues/199 . It looks like that issue shouldn't have been closed.

**Comment by Dignifiedquire** [comment]
Should be fixed in the latest version
