### ISSUE TITLE
Self signed certificate in chain

### ISSUE THREAD

**Issue by blemaire** [karma-runner/karma#1386]
Hi everyone

Trying to install Karma to start angular testing but I run into the following error:
```
npm install karma --save-dev
npm ERR! fetch failed https://registry.npmjs.org/karma/-/karma-0.12.31.tgz
npm WARN retry will retry, error on last attempt: Error: self signed certificate in certificate chain
npm ERR! fetch failed https://registry.npmjs.org/karma/-/karma-0.12.31.tgz
npm WARN retry will retry, error on last attempt: Error: self signed certificate in certificate chain
npm ERR! fetch failed https://registry.npmjs.org/karma/-/karma-0.12.31.tgz
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "karma" "--save-dev"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\reapit\prog\mobile\resources\npm-debug.log


HERE IS THE CONTENT OF npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'karma',
1 verbose cli   '--save-dev' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 silly cache add args [ 'karma', null ]
6 verbose cache add spec karma
7 silly cache add parsed spec { raw: 'karma',
7 silly cache add   scope: null,
7 silly cache add   name: 'karma',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed karma@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'karma', range: '*', hasData: false }
12 silly mapToRegistry name karma
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/karma
16 verbose addNameRange registry:https://registry.npmjs.org/karma not in flight; fetching
17 verbose request uri https://registry.npmjs.org/karma
18 verbose request no auth needed
19 info attempt registry request try #1 at 10:10:40 AM
20 verbose request id 28c1930524876bf4
21 verbose etag "3LMNVL5QGR1DYJOZTQOE7SSOJ"
22 http request GET https://registry.npmjs.org/karma
23 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
24 info attempt registry request try #2 at 10:10:50 AM
25 verbose etag "3LMNVL5QGR1DYJOZTQOE7SSOJ"
26 http request GET https://registry.npmjs.org/karma
27 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
28 info attempt registry request try #3 at 10:11:51 AM
29 verbose etag "3LMNVL5QGR1DYJOZTQOE7SSOJ"
30 http request GET https://registry.npmjs.org/karma
31 silly get cb [ 304, undefined ]
32 verbose etag https://registry.npmjs.org/karma from cache
33 verbose get saving karma to C:\Users\blemaire\AppData\Roaming\npm-cache\registry.npmjs.org\karma\.cache.json
34 silly addNameRange number 2 { name: 'karma', range: '*', hasData: true }
35 silly addNameRange versions [ 'karma',
35 silly addNameRange   [ '0.8.0',
35 silly addNameRange     '0.9.0-dart',
35 silly addNameRange     '0.8.1',
35 silly addNameRange     '0.8.2',
35 silly addNameRange     '0.8.3',
35 silly addNameRange     '0.9.0',
35 silly addNameRange     '0.8.4',
35 silly addNameRange     '0.9.1',
35 silly addNameRange     '0.8.5',
35 silly addNameRange     '0.9.2',
35 silly addNameRange     '0.9.2-dart',
35 silly addNameRange     '0.9.3',
35 silly addNameRange     '0.8.6',
35 silly addNameRange     '0.9.4',
35 silly addNameRange     '0.8.7',
35 silly addNameRange     '0.9.5',
35 silly addNameRange     '0.9.6',
35 silly addNameRange     '0.8.8',
35 silly addNameRange     '0.9.7',
35 silly addNameRange     '0.9.8',
35 silly addNameRange     '0.10.0',
35 silly addNameRange     '0.10.1',
35 silly addNameRange     '0.10.2',
35 silly addNameRange     '0.11.0',
35 silly addNameRange     '0.11.1',
35 silly addNameRange     '0.10.3',
35 silly addNameRange     '0.10.4',
35 silly addNameRange     '0.11.2',
35 silly addNameRange     '0.11.3',
35 silly addNameRange     '0.10.5',
35 silly addNameRange     '0.11.4',
35 silly addNameRange     '0.11.5',
35 silly addNameRange     '0.10.6',
35 silly addNameRange     '0.11.6',
35 silly addNameRange     '0.10.7',
35 silly addNameRange     '0.11.7',
35 silly addNameRange     '0.11.8',
35 silly addNameRange     '0.11.9',
35 silly addNameRange     '0.10.8',
35 silly addNameRange     '0.11.10',
35 silly addNameRange     '0.11.11',
35 silly addNameRange     '0.11.12',
35 silly addNameRange     '0.11.11-dev',
35 silly addNameRange     '0.10.9',
35 silly addNameRange     '0.11.12-dev',
35 silly addNameRange     '0.11.12-dev2',
35 silly addNameRange     '0.11.13',
35 silly addNameRange     '0.11.14',
35 silly addNameRange     '0.12.0',
35 silly addNameRange     '0.10.10',
35 silly addNameRange     '0.12.1',
35 silly addNameRange     '0.12.2',
35 silly addNameRange     '0.12.3',
35 silly addNameRange     '0.12.4',
35 silly addNameRange     '0.12.5',
35 silly addNameRange     '0.12.6',
35 silly addNameRange     '0.12.6-beta-43e6e28',
35 silly addNameRange     '0.12.7',
35 silly addNameRange     '0.12.8',
35 silly addNameRange     '0.12.9',
35 silly addNameRange     '0.12.10',
35 silly addNameRange     '0.12.11',
35 silly addNameRange     '0.12.12',
35 silly addNameRange     '0.12.11-beta-3029418',
35 silly addNameRange     '0.12.13',
35 silly addNameRange     '0.12.14',
35 silly addNameRange     '0.12.15',
35 silly addNameRange     '0.12.16',
35 silly addNameRange     '0.12.16-beta-905422d',
35 silly addNameRange     '0.12.17',
35 silly addNameRange     '0.12.18',
35 silly addNameRange     '0.12.19',
35 silly addNameRange     '0.12.20',
35 silly addNameRange     '0.12.21',
35 silly addNameRange     '0.12.22',
35 silly addNameRange     '0.12.23',
35 silly addNameRange     '0.12.24',
35 silly addNameRange     '0.12.24-beta-6cf7955',
35 silly addNameRange     '0.12.25',
35 silly addNameRange     '0.12.25-beta-37a7958',
35 silly addNameRange     '0.12.25-beta-ad5bc24',
35 silly addNameRange     '0.12.26',
35 silly addNameRange     '0.12.27',
35 silly addNameRange     '0.12.28',
35 silly addNameRange     '0.12.28-beta-b9be580',
35 silly addNameRange     '0.12.29',
35 silly addNameRange     '0.12.30',
35 silly addNameRange     '0.12.31',
35 silly addNameRange     '0.12.28-beta-f65c864',
35 silly addNameRange     '0.12.24-dev-test',
35 silly addNameRange     '0.12.24-dev-socketio10',
35 silly addNameRange     '0.12.24-dev-socketio10-2',
35 silly addNameRange     '0.12.32-beta.0',
35 silly addNameRange     '0.12.32' ] ]
36 verbose addNamed karma@0.12.31
37 silly addNamed semver.valid 0.12.31
38 silly addNamed semver.validRange 0.12.31
39 silly mapToRegistry name karma
40 silly mapToRegistry using default registry
41 silly mapToRegistry registry https://registry.npmjs.org/
42 silly mapToRegistry uri https://registry.npmjs.org/karma
43 verbose addRemoteTarball https://registry.npmjs.org/karma/-/karma-0.12.31.tgz not in flight; adding
44 verbose addRemoteTarball [ 'https://registry.npmjs.org/karma/-/karma-0.12.31.tgz',
44 verbose addRemoteTarball   '806aa7c2acb13a39edb9374a7a477e643a5e94c9' ]
45 info retry fetch attempt 1 at 10:11:51 AM
46 info attempt registry request try #1 at 10:11:51 AM
47 http fetch GET https://registry.npmjs.org/karma/-/karma-0.12.31.tgz
48 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
49 info attempt registry request try #2 at 10:12:01 AM
50 http fetch GET https://registry.npmjs.org/karma/-/karma-0.12.31.tgz
51 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
52 info attempt registry request try #3 at 10:13:01 AM
53 http fetch GET https://registry.npmjs.org/karma/-/karma-0.12.31.tgz
54 error fetch failed https://registry.npmjs.org/karma/-/karma-0.12.31.tgz
55 warn retry will retry, error on last attempt: Error: self signed certificate in certificate chain
56 info retry fetch attempt 2 at 10:13:15 AM
57 info attempt registry request try #1 at 10:13:15 AM
58 http fetch GET https://registry.npmjs.org/karma/-/karma-0.12.31.tgz
59 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
60 info attempt registry request try #2 at 10:13:25 AM
61 http fetch GET https://registry.npmjs.org/karma/-/karma-0.12.31.tgz
62 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
63 info attempt registry request try #3 at 10:14:25 AM
64 http fetch GET https://registry.npmjs.org/karma/-/karma-0.12.31.tgz
65 error fetch failed https://registry.npmjs.org/karma/-/karma-0.12.31.tgz
66 warn retry will retry, error on last attempt: Error: self signed certificate in certificate chain
67 info retry fetch attempt 3 at 10:15:28 AM
68 info attempt registry request try #1 at 10:15:28 AM
69 http fetch GET https://registry.npmjs.org/karma/-/karma-0.12.31.tgz
70 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
71 info attempt registry request try #2 at 10:15:39 AM
72 http fetch GET https://registry.npmjs.org/karma/-/karma-0.12.31.tgz
73 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
74 info attempt registry request try #3 at 10:16:40 AM
75 http fetch GET https://registry.npmjs.org/karma/-/karma-0.12.31.tgz
76 error fetch failed https://registry.npmjs.org/karma/-/karma-0.12.31.tgz
77 verbose stack Error: self signed certificate in certificate chain
77 verbose stack     at Error (native)
77 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
77 verbose stack     at TLSSocket.emit (events.js:104:17)
77 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:460:8)
78 verbose cwd C:\reapit\prog\mobile\resources
79 error Windows_NT 6.1.7601
80 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "karma" "--save-dev"
81 error node v0.12.2
82 error npm  v2.7.4
83 error code SELF_SIGNED_CERT_IN_CHAIN
84 error self signed certificate in certificate chain
85 error If you need help, you may report this error at:
85 error     <https://github.com/npm/npm/issues>
86 verbose exit [ 1, true ]
```

Thanks a lot for your help
Bastien

**Comment by Dignifiedquire** [comment]
This looks like an issue with npm rather then karma. Please report it here: https://github.com/npm/npm if you think this is actually a bug, but it just might be that something is not okay with your local connection.
