### ISSUE TITLE
Issues in creating a new karma plugin. 

### ISSUE THREAD

**Issue by antsmartian** [karma-runner/karma#1435]
Hi I'm trying to create an karma plugin. Looks like I'm missing something down the line. 

My `package.json` is

```
{
  "name": "testing",
  "version": "0.0.1",
  "description": "Test",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "grooscript",
    "karma-grooscript"
  ],
  "devDependencies": {
    "karma": "^0.12.36",
    "grooscript" : "1.1.1"
  }
}
```

and my `index.js` is:

```
var path = require('path');

var pattern = function(file) {
    return {pattern: file, included: true, served: true, watched: false};
};

var framework = function(files) {
    files.unshift(pattern(path.join(__dirname, 'adapter.js')));
    files.unshift(pattern(path.resolve(require.resolve('grooscript'), '../grooscript.js')));
};

framework.$inject = ['config.files'];
module.exports = {'framework:testing': ['factory', framework]};
```

and my `adapter.js` is:

```
var gs;
(function(window) {
    window.gs = window.gs;
})(window);
```

All these files reside in a parent directory something like this:

```
testing/
    index.js
    adapter.js
    package.json
```

And in order to test them, I created an sample karma project. I installed the above plugin in the sample karma project like this:

```
npm link ../testing
```

which does install it (could able to see under the `node_module` directory). Then in the karma `config.js`, I added `testing` as frameworks:

```
module.exports = function(config) {
  config.set({
    // base path, that will be used to resolve files and exclude
    basePath: '',

    frameworks: ['jasmine', 'dojo',"testing"] // <--- here
```

Once done, if I run the karma like:

```
karma start
```

I get an error like this:

```
/Users/user/programs/groovy/grooscript/esri-karma-tutorial/node_modules/karma/node_modules/di/lib/injector.js:9
      throw error('No provider for "' + name + '"!');
            ^
Error: No provider for "framework:testing"! (Resolving: framework:testing)
    at error (/Users/user/programs/groovy/grooscript/esri-karma-tutorial/node_modules/karma/node_modules/di/lib/injector.js:22:68)
    at Object.parent.get (/Users/user/programs/groovy/grooscript/esri-karma-tutorial/node_modules/karma/node_modules/di/lib/injector.js:9:13)
    at get (/Users/user/programs/groovy/grooscript/esri-karma-tutorial/node_modules/karma/node_modules/di/lib/injector.js:54:19)
```

where I'm making mistake?

**Comment by maksimr** [comment]
@antoaravinth How look your full `karma.conf.js` file?

Thanks!

**Comment by antoaravinth** [comment]
Here we go:

```
module.exports = function(config) {
  config.set({
    // base path, that will be used to resolve files and exclude
    basePath: '',

    frameworks: ['jasmine', 'dojo',"testing"],

    // list of files / patterns to load in the browser
    files: [
      'spec/main.js',

      // all the sources, tests
      {pattern: 'src/**/*.js', included: false},
      {pattern: 'spec/*.js', included: false}
    ],


    // uncomment the following for code coverage
    // preprocessors: {
    //   // source files, that you wanna generate coverage for
    //   // do not include tests or libraries
    //   // (these files will be instrumented by Istanbul)
    //   'src/**/*.js': ['coverage']
    // },


    // test results reporter to use
    // possible values: dots || progress
    reporters: [
      'dots'
      // uncomment the following line for code coverage
      // , 'coverage'
    ],


    // web server port
    port: 9876,

    // proxy for cross domain requests
    proxies:  {
      '/arcgis/': 'http://imagery.arcgisonline.com/arcgis/'
    },


    // cli runner port
    runnerPort: 9100,


    // enable / disable colors in the output (reporters and logs)
    colors: true,


    // level of logging
    // possible values: LOG_DISABLE || LOG_ERROR || LOG_WARN || LOG_INFO || LOG_DEBUG
    logLevel: config.LOG_INFO,


    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: true,

    // Start these browsers, currently available:
    // - Chrome
    // - ChromeCanary
    // - Firefox
    // - Opera
    // - Safari
    // - PhantomJS
    // NOTE: you may need to first set it's path in an environment vairable, for example:
    // set FIREFOX_BIN="c:\Program Files (x86)\Mozilla Firefox\firefox.exe"
    // see: http://karma-runner.github.io/0.10/config/browsers.html
    browsers: [
      'Chrome'
      // add the name (from above) for each additional
      // browser you want to test below
      // , 'Firefox'
    ],


    // uncomment the following for coverage options
    // see: https://github.com/karma-runner/karma-coverage#options
    // coverageReporter: {
    //   type : 'text',
    //   dir: 'coverage/'
    // },


    // Continuous Integration mode
    // if true, it capture browsers, run tests and exit
    singleRun: false
  });
};
```

If you want to have a look at the complete karma project, I cloned it from here : https://github.com/tomwayson/esri-karma-tutorial

**Comment by maksimr** [comment]
@antoaravinth and where located your plugin relate to this project?
karma by default look plugins in `node_modules` with prefix `karma-`

**Comment by antoaravinth** [comment]
@maksimr : Thanks, looks like I named the module as `testing` and hence `karma` wasn't picking. Changing the name with prefix `karma-` works. 

However I see some minor issue in the `adapter.js` : 

```
(function(window) {
   console.log(window.gs)
    window.gs = window.gs;
})(window);
```

the `console.log` does print the `window.gs` to correct groovy script fn. 

However if I do : 

```
gs // or window.gs
```

in the console, I see its `undefined`. I'm getting confusion now. If it could print `window.gs`, why not I cant access it via console. Am I missing something here?

**Comment by maksimr** [comment]
@antoaravinth it's strange `gs` should be defined, because in your index.js
grooscript load before adapter.js

```js
var framework = function(files) {
    files.unshift(pattern(path.join(__dirname, 'adapter.js')));
    files.unshift(pattern(path.resolve(require.resolve('grooscript'), '../grooscript.js')));
};
```

You can try debug this behavior on `debug.html`(http://localhost:9876/debug.html) page.

**Comment by antoaravinth** [comment]
@maksimr : Thanks for your help. However in the debug page, I could able to see `gs` defined. But not in the karma running context. I'm confused. 

Any ideas, of why does this would happen?

**Comment by Dignifiedquire** [comment]
I'm supsecting your code gets executed in the test iframe rather than the outside frame (which is where the default karma window console drops you in) so if you want to debug from that frame you can use the iframe context switcher in the devtools to drop into the iframe and there window.hs should be defined

**Comment by devoto13** [comment]
Closing as answered.
