### ISSUE TITLE
 Can not load "webpack"

### ISSUE THREAD

**Issue by kof** [karma-runner/karma#1497]
https://stackoverflow.com/questions/31444743/karma-cant-load-webpack/31452564

Its reproducible when you install all the latest versions of karma-* on node v2.3.4

**Comment by AlexKVal** [comment]
`react-bootstrap/react-bootstrap` same issue.

**Comment by Dignifiedquire** [comment]
Thanks for the report, I will look into it as soon as I can

**Comment by Dignifiedquire** [comment]
Can you please check if this is still an issue in `0.13.1`

**Comment by mateatslc** [comment]
@Dignifiedquire yep, still seeing it with v0.13.1

**Comment by tehnomaag** [comment]
I'm also still having the same issue. My project tried to closely follow [this example project](https://github.com/justinwoo/react-karma-webpack-testing).

```
erki at mac in /Volumes/code/experiments/modern-react
$ <node_modules/karma/package.json | grep version
  "version": "0.13.1",
```

```
erki at mac in /Volumes/code/experiments/modern-react
$ karma start
16 07 2015 22:43:10.756:WARN [preprocess]: Can not load "webpack"!
  Error: Can not resolve circular dependency! (Resolving: preprocessor:webpack -> webpackPlugin -> preprocessor:webpack)
    at error (/Volumes/code/experiments/modern-react/node_modules/karma/node_modules/di/lib/injector.js:22:68)
    at get (/Volumes/code/experiments/modern-react/node_modules/karma/node_modules/di/lib/injector.js:44:15)
    at instantiatePreprocessor (/Volumes/code/experiments/modern-react/node_modules/karma/lib/preprocessor.js:56:37)
    at Array.forEach (native)
    at null.<anonymous> (/Volumes/code/experiments/modern-react/node_modules/karma/lib/preprocessor.js:77:31)
    at tryCatcher (/Volumes/code/experiments/modern-react/node_modules/bluebird/js/main/util.js:26:23)
    at ret [as _preprocess] (eval at <anonymous> (/Volumes/code/experiments/modern-react/node_modules/bluebird/js/main/promisify.js:163:12), <anonymous>:13:39)
    at /Volumes/code/experiments/modern-react/node_modules/karma/lib/file-list.js:183:19
    at Array.map (native)
    at /Volumes/code/experiments/modern-react/node_modules/karma/lib/file-list.js:168:30
    at Array.map (native)
    at List._refresh (/Volumes/code/experiments/modern-react/node_modules/karma/lib/file-list.js:151:37)
    at List.refresh (/Volumes/code/experiments/modern-react/node_modules/karma/lib/file-list.js:250:27)
    at Plugin.notifyKarmaAboutChanges (/Volumes/code/experiments/modern-react/node_modules/karma-webpack/index.js:109:16)
    at Plugin.<anonymous> (/Volumes/code/experiments/modern-react/node_modules/karma-webpack/index.js:73:9)
    at Tapable.applyPlugins (/Volumes/code/experiments/modern-react/node_modules/webpack/node_modules/tapable/lib/Tapable.js:26:37)
16 07 2015 22:43:19.039:INFO [karma]: Karma v0.13.1 server started at http://localhost:9876/
16 07 2015 22:43:19.050:INFO [launcher]: Starting browser Chrome
16 07 2015 22:43:20.323:INFO [Chrome 43.0.2357 (Mac OS X 10.10.4)]: Connected on socket hShBX6sNlGjwOg1oAAAA with id 8720101
.
Chrome 43.0.2357 (Mac OS X 10.10.4): Executed 1 of 1 SUCCESS (0.046 secs / 0.032 secs)
```

My `package.json` relevant deps:

```
    "karma": "^0.13.1",
    "karma-chrome-launcher": "^0.2.0",
    "karma-cli": "^0.1.0",
    "karma-mocha": "^0.2.0",
    "karma-sourcemap-loader": "^0.3.5",
    "karma-webpack": "^1.6.0",
    "mocha": "^2.2.5",
    "webpack": "^1.10.1",
```

**Comment by Uter1007** [comment]
same here :( 

Node v0.12.7

Same Example tried.

**Comment by MichalZalecki** [comment]
To get around this issue downgrade karma. This set up works:
```json
"karma": "^0.12.36",
"karma-chrome-launcher": "^0.2.0",
"karma-html-reporter": "^0.2.6",
"karma-jasmine": "^0.3.6",
"karma-phantomjs-launcher": "^0.2.0",
"karma-webpack": "^1.6.0",
```

**Comment by tshelburne** [comment]
Another working config:

```
"karma": "^0.12.36",
"karma-chrome-launcher": "^0.2.0",
"karma-cli": "^0.1.0",
"karma-mocha": "^0.2.0",
"karma-sourcemap-loader": "^0.3.5",
"karma-webpack": "^1.6.0",
```

**Comment by Dignifiedquire** [comment]
Just a quick update, I was able to find out what the underlying issue is: In short dependency injection sucks. Fix coming soon

**Comment by Dignifiedquire** [comment]
Okay I've just released `0.13.2` that will resolve the issue together with this pr: https://github.com/webpack/karma-webpack/issues/63

**Comment by mateatslc** [comment]
now just have to wait till that PR gets merged... ಠ_ಠ

**Comment by tshelburne** [comment]
Hooray for OSS!

**Comment by haf** [comment]
OT: DI sucks because it exposes cyclic dependencies? I'd say that's a win for DI and by avoiding partial/unreliable initialisation ;)

Happy for fix, would be great to get https://github.com/webpack/karma-webpack/pull/63 merged and released =)

**Comment by tupy** [comment]
@Dignifiedquire closed?

**Comment by Dignifiedquire** [comment]
yep fixed now
