### ISSUE TITLE
TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by albertosantini** [karma-runner/karma#1544]
With 0.13.5. on Travis CI, I get the below message.
Locally, on Windows 10 box, it works fine.

```
Running "karma:continuos" (karma) task
04 08 2015 22:02:57.300:INFO [karma]: Karma v0.13.5 server started at http://localhost:9876/
04 08 2015 22:02:57.306:INFO [launcher]: Starting browser PhantomJS
04 08 2015 22:02:57.535:INFO [PhantomJS 1.9.8 (Linux 0.0.0)]: Connected on socket OVnFFtIiryxYxgx4AAAA with id 12406497
TypeError: Cannot read property 'then' of undefined
    at then (/home/travis/build/albertosantini/argo/node_modules/karma/lib/middleware/common.js:12:19)
    at /home/travis/build/albertosantini/argo/node_modules/karma/lib/middleware/karma.js:107:27
    at call (/home/travis/build/albertosantini/argo/node_modules/karma/node_modules/connect/index.js:239:7)
    at next (/home/travis/build/albertosantini/argo/node_modules/karma/node_modules/connect/index.js:183:5)
    at /home/travis/build/albertosantini/argo/node_modules/karma/lib/middleware/strip_host.js:13:5
    at call (/home/travis/build/albertosantini/argo/node_modules/karma/node_modules/connect/index.js:239:7)
    at next (/home/travis/build/albertosantini/argo/node_modules/karma/node_modules/connect/index.js:183:5)
    at /home/travis/build/albertosantini/argo/node_modules/karma/lib/middleware/runner.js:19:14
    at call (/home/travis/build/albertosantini/argo/node_modules/karma/node_modules/connect/index.js:239:7)
    at next (/home/travis/build/albertosantini/argo/node_modules/karma/node_modules/connect/index.js:183:5)
    at Function.handle (/home/travis/build/albertosantini/argo/node_modules/karma/node_modules/connect/index.js:186:3)
    at Server.app (/home/travis/build/albertosantini/argo/node_modules/karma/node_modules/connect/index.js:51:37)
    at Server.<anonymous> (/home/travis/build/albertosantini/argo/node_modules/karma/node_modules/socket.io/node_modules/engine.io/lib/server.js:369:22)
    at Server.<anonymous> (/home/travis/build/albertosantini/argo/node_modules/karma/node_modules/socket.io/lib/index.js:258:16)
    at emitTwo (events.js:87:13)
    at Server.emit (events.js:172:7)
04 08 2015 22:03:07.537:WARN [PhantomJS 1.9.8 (Linux 0.0.0)]: Disconnected (1 times), because no message in 10000 ms.
PhantomJS 1.9.8 (Linux 0.0.0): Executed 0 of 0 DISCONNECTED (10.007 secs / 0 secs)
Warning: Task "karma:continuos" failed. Use --force to continue.

```

P.S.: with 0.13.3, the test was ok.

P.S.2: Just with another commit, it is ok. Timeout glitch? I close the issue.

**Comment by Dignifiedquire** [comment]
Reopening, as a tracker for the issue mentioned in https://github.com/karma-runner/karma/issues/1520#issuecomment-127783120

**Comment by Dignifiedquire** [comment]
Should be fixed in [v0.13.6](https://github.com/karma-runner/karma/releases/tag/v0.13.6)

**Comment by albertosantini** [comment]
With 0.13.6 I get with Node.js (with io.js is ok) the following message:

  You need to include some adapter that implements __karma__.start method!

Reference: https://travis-ci.org/albertosantini/argo/jobs/74189986

**Comment by Dignifiedquire** [comment]
Looking into it, for some reason this error only appears on travis, but not on my local machines -.-

**Comment by albertosantini** [comment]
Here the same.

Do you prefer I open a new issue?

**Comment by Dignifiedquire** [comment]
Yes let's move this into a new issue, it seems that this is only related to phantomjs (this thing makes more problems than you can imagine). I tried your repo locally and can't get tests running at all using phantomjs (no matter what node or karma version) but when I switch to Chrome all is good :(
