### ISSUE TITLE
Crash with bad >== operator

### ISSUE THREAD

**Issue by BEllis** [karma-runner/karma#1599]
The following line appears to cause Karma or the Karma.Coverage plugin to crash (stops running when single-run is false), where >== is an error in the code under test.

        if (x >== boardSize || x < 0 || y >== boardSize || y < 0) {

The error that is displayed in the log is,

30 09 2015 21:25:53.155:ERROR [preprocessor.coverage]: Line 55: Unexpected token =
  at /Users/ben.ellis/dev/nodetest/src/main/js/BGoUtils.js
30 09 2015 21:25:53.156:ERROR [karma]: [TypeError: Not a string or buffer]
TypeError: Not a string or buffer
    at TypeError (native)
    at Hash.update (crypto.js:119:16)
    at sha1 (/Users/ben.ellis/dev/nodetest/node_modules/karma/lib/preprocessor.js:11:8)
    at nextPreprocessor (/Users/ben.ellis/dev/nodetest/node_modules/karma/lib/preprocessor.js:69:20)
    at /Users/ben.ellis/dev/nodetest/node_modules/karma-coverage/lib/preprocessor.js:140:7
    at Object.Instrumenter.instrument (/Users/ben.ellis/dev/nodetest/node_modules/karma-coverage/node_modules/istanbul/lib/instrumenter.js:585:17)
    at /Users/ben.ellis/dev/nodetest/node_modules/karma-coverage/lib/preprocessor.js:110:18
    at nextPreprocessor (/Users/ben.ellis/dev/nodetest/node_modules/karma/lib/preprocessor.js:73:28)
    at /Users/ben.ellis/dev/nodetest/node_modules/karma/lib/preprocessor.js:96:7
    at /Users/ben.ellis/dev/nodetest/node_modules/karma/node_modules/graceful-fs/graceful-fs.js:76:16
    at fs.js:334:14
    at /Users/ben.ellis/dev/nodetest/node_modules/karma/node_modules/graceful-fs/graceful-fs.js:42:10
    at FSReqWrap.oncomplete (fs.js:95:15)
Refresh: /Users/ben.ellis/dev/nodetest/src/main/js/BGoUtils.js

**Comment by wesleycho** [comment]
This is probably an issue with bad JS combined with karma-coverage based on what the stack trace seems to indicate, not karma.

**Comment by dignifiedquire** [comment]
As @wesleycho said, so closing this.
