### ISSUE TITLE
npm install karma -g  fail

### ISSUE THREAD

**Issue by cyrilchaponeverysens** [karma-runner/karma#1610]
Tested with
```
node --version 4.*
npm --version 3.*
```

```
node --version v0.12.*
npm --version 3.*
```

Out of the box I'm getting this
```
D:\nodejs\karma -> D:\nodejs\node_modules\karma\bin\karma

> bufferutil@1.2.1 install D:\nodejs\node_modules\karma\node_modules\bufferutil
> node-gyp rebuild


D:\nodejs\node_modules\karma\node_modules\bufferutil>if not defined npm_config_node_gyp (node "D:\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Génération des projets individuellement dans cette solution. Pour activer la génération en parallèle, ajoutez le commutateur "/m".
MSBUILD : error MSB3428: Impossible de charger le composant Visual C++ "VCBuild.exe". Pour corriger le problème, vou
s devez 1) installer le Kit de développement .NET Framework 2.0 SDK, 2) installer Microsoft Visual Studio 2005 ou 3)
 ajouter l'emplacement du composant au chemin d'accès système, s'il est installé ailleurs.  [D:\nodejs\node_modules\
karma\node_modules\bufferutil\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "D:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\nodejs\node_modules\karma\node_modules\bufferutil
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
D:\nodejs
└── (empty)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "D:\\nodejs\\\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "karma"
npm ERR! node v0.12.7
npm ERR! npm  v3.3.5
npm ERR! code ELIFECYCLE

npm ERR! bufferutil@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@1.2.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Cyril\Desktop\folder\rtls-frontend\npm-debug.log
npm ERR! code 1
```

It still works with

```
node --version v0.12.*
npm --version 2.*
```

I saw #1609 but I don't think it has something to do with this

**Comment by maksimr** [comment]
@cyrilchaponeverysens try install `bufferutil` latest version and `bufferutil@1.2.1`

Thanks

**Comment by Dignifiedquire** [comment]
Also karma should not be installed globally, if you want a global command use karma-cli globally and karma installed locally.

**Comment by cyrilchaponeverysens** [comment]
Great answers there, thanks.

Gonna dig into it when I have a chance.
