### ISSUE TITLE
Gulp4 + Karma causes a formatError exception

### ISSUE THREAD

**Issue by robertbaker** [karma-runner/karma#1666]
```
var karmaConfig = {
        configFile: __dirname + '/' + config.karma,
        singleRun: true,
        autoWatch: false
    };

gulp.task('test', gulp.series('compile:build', function testing(done) {
    var karma = new plugins.karma.Server(karmaConfig, done);
    karma.start();
}));


// also does this here
 gulp.task('test:ts', function testing(done) {
        var karma = new plugins.karma.Server(karmaConfig, done);
        karma.start();
});

```

```
[14:52:25] Error: 1
    at formatError (C:\Program Files\nodejs\node_modules\gulp-cli\lib\versioned\^4.0.0-alpha.1\formatError.js:20:10)
    at Gulp.<anonymous> (C:\Program Files\nodejs\node_modules\gulp-cli\lib\versioned\^4.0.0-alpha.1\log\events.js:26:15)
    at emitOne (events.js:77:13)
    at Gulp.emit (events.js:169:7)
    at Object.error (c:\git\pos\node_modules\undertaker\lib\helpers\createExtensions.js:58:10)
    at handler (c:\git\pos\node_modules\now-and-later\lib\map.js:46:14)
    at f (c:\git\pos\node_modules\once\once.js:17:25)
    at f (c:\git\pos\node_modules\once\once.js:17:25)
    at done (c:\git\pos\node_modules\async-done\index.js:24:15)
    at f (c:\git\pos\node_modules\once\once.js:17:25)
    at handler (c:\git\pos\node_modules\now-and-later\lib\mapSeries.js:44:16)
    at f (c:\git\pos\node_modules\once\once.js:17:25)
    at f (c:\git\pos\node_modules\once\once.js:17:25)
    at done (c:\git\pos\node_modules\async-done\index.js:24:15)
    at removeAllListeners (c:\git\pos\node_modules\karma\lib\server.js:332:7)
    at Server.<anonymous> (c:\git\pos\node_modules\karma\lib\server.js:343:9)
```

**Comment by Dignifiedquire** [comment]
when karma fails it calls the done callback with the exit code of `1`. So if you want gulp to interpret this different you need to change your callback and check for the exit code and then pass an error to gulp.
