### ISSUE TITLE
Latest socket.io has broken Karma

### ISSUE THREAD

**Issue by deenairn** [karma-runner/karma#1785]
Finding some errors on our TeamCity build due to the update to socket.io. Resolved these by adding a local dependency on socket.io 1.3.7.

[Step 6/7] Missing error handler on `socket`.
[12:12:35][Step 6/7] TypeError: undefined is not a function
[12:12:35][Step 6/7]     at disconnectBrowsers (C:\Project\node_modules\karma\lib\server.js:314:13)
[12:12:35][Step 6/7]     at null.<anonymous> (C:\Project\node_modules\karma\lib\server.js:291:7)
[12:12:35][Step 6/7]     at emit (events.js:129:20)
[12:12:35][Step 6/7]     at emitRunCompleteIfAllBrowsersDone (C:\Project\node_modules\karma\lib\server.js:256:12)
[12:12:35][Step 6/7]     at null.<anonymous> (C:\Project\node_modules\karma\lib\server.js:278:9)
[12:12:35][Step 6/7]     at emit (events.js:129:20)
[12:12:35][Step 6/7]     at onComplete (C:\Project\node_modules\karma\lib\browser.js:142:13)
[12:12:35][Step 6/7]     at Socket.<anonymous> (C:\Project\node_modules\karma\lib\events.js:13:22)
[12:12:35][Step 6/7]     at Socket.emit (events.js:129:20)
[12:12:35][Step 6/7]     at Socket.onevent (C:\Project\node_modules\karma\node_modules\socket.io\lib\socket.js:335:8)
[12:12:35][Step 6/7]     at Socket.onpacket (C:\Project\node_modules\karma\node_modules\socket.io\lib\socket.js:295:12)
[12:12:35][Step 6/7]     at Client.ondecoded (C:\Project\node_modules\karma\node_modules\socket.io\lib\client.js:193:14)
[12:12:35][Step 6/7]     at Decoder.Emitter.emit (C:\Project\node_modules\karma\node_modules\socket.io\node_modules\socket.io-parser\node_modules\component-emitter\index.js:134:20)
[12:12:35][Step 6/7]     at Decoder.add (C:\Project\node_modules\karma\node_modules\socket.io\node_modules\socket.io-parser\index.js:247:12)
[12:12:35][Step 6/7]     at Client.ondata (C:\Project\node_modules\karma\node_modules\socket.io\lib\client.js:175:18)
[12:12:35][Step 6/7]     at Socket.emit (events.js:107:17)

**Comment by Dignifiedquire** [comment]
Already fixed in the latest release see #1784 and #1782

**Comment by deenairn** [comment]
Beat me to the punch there - realised there's a new release now - we were on 0.13.15 - fixed for me in 0.13.19. :+1:
