### ISSUE TITLE
karma init getting exception

### ISSUE THREAD

**Issue by nmellempudi** [karma-runner/karma#1905]
I just installed karma and trying 

karma init karma.conf.js

Getting below exception. node.js version is 0.10.32

```
$ karma init karma2.conf.js

net.js:156
    this._handle.open(options.fd);
                 ^
Error: EINVAL, invalid argument
  at new Socket (net.js:156:18)
  at process.stdin (node.js:664:19)
  at Object.exports.init (E:\experimental\vs15\node_modules\karma\lib\init.js:230:10)
  at Object.exports.run (E:\experimental\vs15\node_modules\karma\lib\cli.js:249:25)
  at requireCliAndRun (C:\Users\nmellemp\AppData\Roaming\npm\node_modules\karma-cli\bin\karma:44:16)
  at C:\Users\nmellemp\AppData\Roaming\npm\node_modules\karma-cli\bin\karma:54:12
  at C:\Users\nmellemp\AppData\Roaming\npm\node_modules\karma-cli\node_modules\resolve\lib\async.js:44:21
  at ondir (C:\Users\nmellemp\AppData\Roaming\npm\node_modules\karma-cli\node_modules\resolve\lib\async.js:187:31)
  at C:\Users\nmellemp\AppData\Roaming\npm\node_modules\karma-cli\node_modules\resolve\lib\async.js:153:39
  at onex (C:\Users\nmellemp\AppData\Roaming\npm\node_modules\karma-cli\node_modules\resolve\lib\async.js:93:22)
  at C:\Users\nmellemp\AppData\Roaming\npm\node_modules\karma-cli\node_modules\resolve\lib\async.js:24:18
  at Object.oncomplete (fs.js:107:15)
```

**Comment by dignifiedquire** [comment]
Can you try with a new version of node and the latest version of karma?

**Comment by EzraBrooks** [comment]
It's been over a year with no additional discussion, closing.
