### ISSUE TITLE
Object [object Object] has no method 'forEach'

### ISSUE THREAD

**Issue by glipecki** [karma-runner/karma#1910]
Exception while executing karma tests on phantom.

Versions:
- karma: 0.13.14
- phantomjs: 1.9.18
- grunt: 0.4.5
- node: 0.10.40
- grunt-karma: 0.12.1

Any ideas?

Output:
```
Running "karma:phantom" (karma) task

Start:
  webforms url builder
    ✔ should canonicalize
    ✔ should add first param
    ✔ should add next param
  console logger
    ✔ should log anything
    ✔ should evaluate parameter in message
    ✔ should evaluate multiple parameters in message

Finished in 0.041 secs / 0.003 secs

SUMMARY:
✔ 6 tests completed
Missing error handler on `socket`.
TypeError: Object [object Object] has no method 'forEach'
    at disconnectBrowsers (/home/users/glipecki/eximee/workspace/eximee-flow-m/eximee-flow-m-ui/node_modules/karma/lib/server.js:314:13)
    at null.<anonymous> (/home/users/glipecki/eximee/workspace/eximee-flow-m/eximee-flow-m-ui/node_modules/karma/lib/server.js:291:7)
    at emit (events.js:117:20)
    at emitRunCompleteIfAllBrowsersDone (/home/users/glipecki/eximee/workspace/eximee-flow-m/eximee-flow-m-ui/node_modules/karma/lib/server.js:256:12)
    at null.<anonymous> (/home/users/glipecki/eximee/workspace/eximee-flow-m/eximee-flow-m-ui/node_modules/karma/lib/server.js:278:9)
    at emit (events.js:117:20)
    at onComplete (/home/users/glipecki/eximee/workspace/eximee-flow-m/eximee-flow-m-ui/node_modules/karma/lib/browser.js:142:13)
    at Socket.<anonymous> (/home/users/glipecki/eximee/workspace/eximee-flow-m/eximee-flow-m-ui/node_modules/karma/lib/events.js:13:22)
    at Socket.emit (events.js:117:20)
    at Socket.onevent (/home/users/glipecki/eximee/workspace/eximee-flow-m/eximee-flow-m-ui/node_modules/karma/node_modules/socket.io/lib/socket.js:335:8)
    at Socket.onpacket (/home/users/glipecki/eximee/workspace/eximee-flow-m/eximee-flow-m-ui/node_modules/karma/node_modules/socket.io/lib/socket.js:295:12)
    at Client.ondecoded (/home/users/glipecki/eximee/workspace/eximee-flow-m/eximee-flow-m-ui/node_modules/karma/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/home/users/glipecki/eximee/workspace/eximee-flow-m/eximee-flow-m-ui/node_modules/karma/node_modules/socket.io/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/home/users/glipecki/eximee/workspace/eximee-flow-m/eximee-flow-m-ui/node_modules/karma/node_modules/socket.io/node_modules/socket.io-parser/index.js:247:12)
    at Client.ondata (/home/users/glipecki/eximee/workspace/eximee-flow-m/eximee-flow-m-ui/node_modules/karma/node_modules/socket.io/lib/client.js:175:18)
    at Socket.emit (events.js:95:17)
16 02 2016 13:11:58.524:WARN [PhantomJS 1.9.8 (Linux 0.0.0)]: Disconnected (1 times), because no message in 10000 ms.
```

**Comment by dignifiedquire** [comment]
Could you test if this still happens on the latest version of karma?

**Comment by glipecki** [comment]
All works great with karma 0.13.21, thanks for your help :-)
It's a suprise becouse old version worked ok two weeks ago ;)
