### ISSUE TITLE
No `customContextFile` causes Windows to fail

### ISSUE THREAD

**Issue by twolfson** [karma-runner/karma#2000]
I'm developing `karma-electron` with a fork off of `master` which uses #1984. I noticed that AppVeyor is failing while Travis CI is passing and it didn't do this on `0.13.22`.

**Failure on `master` fork:**

https://ci.appveyor.com/project/twolfson/karma-electron-launcher/build/job/a2glw31p686akewh

**Success on `0.13.22`:**

https://ci.appveyor.com/project/twolfson/karma-electron-launcher/build/80/job/ugvxnlxy518qy30n

After a bit of debugging, I realized this was due to us not doing a `null` check in `helper.normalizeWinPath`:

https://github.com/karma-runner/karma/blob/v0.13.22/lib/helper.js#L71-L75

https://github.com/karma-runner/karma/blob/b2cb31a204a295770f845384ea12fbbe0ad8e0d6/lib/config.js#L117-L118

### Expected behavior
- Ran `karma` and received following error:

```
C:\projects\karma-electron-launcher\node_modules\karma\lib\helper.js:72
  return exports.isDefined(path) ? path.replace(/\\/g, '/') : path
                                        ^
TypeError: Cannot call method 'replace' of null
    at Object.replaceWinPath [as normalizeWinPath] (C:\projects\karma-electron-launcher\node_modules\karma\lib\helper.js:72:41)
    at normalizeConfig (C:\projects\karma-electron-launcher\node_modules\karma\lib\config.js:119:37)
    at Object.parseConfig (C:\projects\karma-electron-launcher\node_modules\karma\lib\config.js:335:10)
    at new Server (C:\projects\karma-electron-launcher\node_modules\karma\lib\server.js:56:20)
    at Object.exports.run (C:\projects\karma-electron-launcher\node_modules\karma\lib\cli.js:262:7)
    at Object.<anonymous> (C:\projects\karma-electron-launcher\node_modules\karma\bin\karma:3:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

### Actual behavior
- Expected `karma` to pass without errors

### Enviroment Details
- Karma version (output of `karma --version`): Derivative off of `master` (post-`0.13.22`)
- Relevant part of your `karma.config.js` file: N/A

### Steps to reproduce the behaviour
Here's what I'm doing but there's prob a better way to handle this (e.g. IE VMs):

1. Fork `karma-electron`
2. Enable AppVeyor for fork
3. Run a build and see it fail

### Recommendations
To prevent things like this landing on `master`, I suggest we set up CI with AppVeyor in addition to the current Travis CI. This can be simple like only running `grunt test` but it should catch issues like this one.

**Comment by twolfson** [comment]
I will be submitting a PR to patch this shortly

**Comment by twolfson** [comment]
PR #2001 has been opened to resolve this issue
