### ISSUE TITLE
file-list.js exception

### ISSUE THREAD

**Issue by jnoring** [karma-runner/karma#2105]
When I go to run tests, I get the following error:

```
/Users/jnoring/hirevue/licode/erizo_controller/erizoClient/node_modules/karma/lib/file-list.js:199
  .cancellable()
   ^
TypeError: Object [object Promise] has no method 'cancellable'
    at List._refresh (/Users/jnoring/hirevue/licode/erizo_controller/erizoClient/node_modules/karma/lib/file-list.js:199:4)
    at List.refresh (/Users/jnoring/hirevue/licode/erizo_controller/erizoClient/node_modules/karma/lib/file-list.js:252:27)
    at Server._start (/Users/jnoring/hirevue/licode/erizo_controller/erizoClient/node_modules/karma/lib/server.js:178:12)
    at invoke (/Users/jnoring/hirevue/licode/erizo_controller/erizoClient/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at Server.start (/Users/jnoring/hirevue/licode/erizo_controller/erizoClient/node_modules/karma/lib/server.js:102:18)
    at Object.exports.run (/Users/jnoring/hirevue/licode/erizo_controller/erizoClient/node_modules/karma/lib/cli.js:243:26)
    at Object.<anonymous> (/Users/jnoring/hirevue/licode/erizo_controller/erizoClient/node_modules/karma/bin/karma:3:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
```

I think the problem is package.json specifies a version of bluebird (3.3.5) that no longer supports this, but the lib file in the npm package still contains file-list.js that includes a call to `.cancellable()`.  I see on master that has been removed, but the npm package for 0.13.22 _still_ contains it.

### Enviroment Details

Karma version: 0.13.22

**Comment by jnoring** [comment]
Nevermind--I think it's some weird artifact of install on OSX.  Very strange though.

**Comment by maxmarkus** [comment]
Never mix node_modules with once that rely on newer ones. Our build was broken, because we also added 3.x bluebird to package.json and had "karma": "0.13.19" in place too. 
But `npm list bluebird` showed that karma relied on 2.10.x and seems it did not access that version, but the newer one.
