### ISSUE TITLE
Karma 'mtime' Error -- Issue 1494 not fixed

### ISSUE THREAD

**Issue by mgreezy** [karma-runner/karma#2158]
This issue seems to be a duplicate of [Issue 1494](https://github.com/karma-runner/karma/issues/1494) which was deemed resolved (I have commented in that Issue and will edit to reference this issue number).

While attempting to run Karma (v. 0.13.3) via Gulp (v. 1.2.1) using Node (v. 6.0.0), there is a reported warning followed by a crash. The warning states "Cannot read property 'mtime' of undefined Use" as shown in the screenshot below.

![image](https://cloud.githubusercontent.com/assets/8759878/15678240/8bfd4688-271b-11e6-9d96-c037ba6ba454.png)

Please let me know if any further information would be helpful toward resolution of this issue.

**Comment by dignifiedquire** [comment]
Version `0.13.3` is quite old could you update the latest version please (`0.13.22`)

**Comment by mgreezy** [comment]
Thank you for your response @dignifiedquire .

I have updated to the latest version of Karma (0.13.22), however I am still receiving the same error when running unit tests.

I forgot to mention that I am working on angular-fullstack generated from yeoman.

**Comment by djdawson3** [comment]
I'm having the same issue as well with Karma 0.13.22 and gulp 1.2.1.

**Comment by tjama** [comment]
I got the same issue with karma 0.13.22, node 6.2.1 and grunt-karma 2.0 on Win7. Here is stack trace:

```
node_modules\karma\lib\file-list.js:176
      var mtime = mg.statCache[path].mtime
                                    ^

TypeError: Cannot read property 'mtime' of undefined
    at node_modules\karma\lib\file-list.js:176:37
    at Array.map (native)
    at node_modules\karma\lib\file-list.js:170:30
    at Array.map (native)
    at List._refresh (node_modules\karma\lib\file-list.js:153:37)
    at List.refresh (node_modules\karma\lib\file-list.js:252:27)
    at Server._start (node_modules\karma\lib\server.js:178:12)
```

**Comment by Macrofig** [comment]
Just in case it is helpful to others, I was running into the same error. The problem was in my the file pattern I was using to target my test files. Seems like something changed in https://www.npmjs.com/package/glob. Maybe take a second look at your pattern to verify Glob returns something?

**Comment by sjerman** [comment]
OK... so I have the same issue:

Adding some traces, this glob was causing the problem for me
  'main/webapp/scripts/components/**/*.{js,html}',

Looking further, the glob found a series of files... and the first(?) html file provoked the error. Removing the 'html' from the glob and it works... seems like it is an issue with glob

**Comment by Macrofig** [comment]
Welp. Thought it was a pattern issue. Wasn't correct... wasn't wrong either, I suppose. We recently updated Glob from 5.x to 7.x and are facing this issue. Also updating Karma from 0.12.31 to latest which also happened to make a big jump in Glob version (version 3.x to 7.x).

I think I've narrowed down the change to this issue: https://github.com/isaacs/node-glob/issues/158 and the matching PR: https://github.com/isaacs/node-glob/pull/159

A possible solution in Karma would be to check if the statCache for the specific path exists [here](https://github.com/karma-runner/karma/blob/master/lib/file-list.js#L176). If not, then populate the stat manually. :(

I have a [test repo](https://github.com/Macrofig/glob-test) that I used to open an [issue with Glob](https://github.com/isaacs/node-glob/issues/265), if anyone has input, I'd appreciate it.

**Comment by fbengrid** [comment]
hiya,

not sure if you did see my comments back then like this one: https://github.com/karma-runner/karma/issues/1494#issuecomment-122330174 but changing the pattern did solve the issue.

This involves replacing the accolades with parenthesis and the comma with | 
In your example this would translate into changing :
`main/webapp/scripts/components/**/*.{js,html}`
to 
`main/webapp/scripts/components/**/*+.(js|html)`

**Comment by dignifiedquire** [comment]
@Macrofig thanks for filing the issue with glob, the fix should ultimately happen in there. In the meantime I agree we should check if it exists and stat manually if it does not.
