### ISSUE TITLE
Error when file is empty or commented out

### ISSUE THREAD

**Issue by Kavorka79** [karma-runner/karma#2160]
### Expected behavior
Skipp empty or commented out file
### Actual behavior

printed out msg in this instance:  { originalErr: {} }
```
Fails with error 
Missing error handler on `socket`.
TypeError: (msg || "").replace is not a function
    at C:\Work\Pixie\src\Pixie\node_modules\karma\lib\reporter.js:46:23
    at onBrowserError (C:\Work\Pixie\src\Pixie\node_modules\karma\lib\reporters\base.js:58:60)
    at null.<anonymous> (C:\Work\Pixie\src\Pixie\node_modules\karma\lib\events.js:13:22)
    at emitTwo (events.js:100:13)
    at emit (events.js:185:7)
    at onKarmaError (C:\Work\Pixie\src\Pixie\node_modules\karma\lib\browser.js:95:13)
    at Socket.<anonymous> (C:\Work\Pixie\src\Pixie\node_modules\karma\lib\events.js:13:22)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at Socket.onevent (C:\Work\Pixie\src\Pixie\node_modules\socket.io\lib\socket.js:335:8)
    at Socket.onpacket (C:\Work\Pixie\src\Pixie\node_modules\socket.io\lib\socket.js:295:12)
    at Client.ondecoded (C:\Work\Pixie\src\Pixie\node_modules\socket.io\lib\client.js:193:14)
    at Decoder.Emitter.emit (C:\Work\Pixie\src\Pixie\node_modules\component-emitter\index.js:134:20)
    at Decoder.add (C:\Work\Pixie\src\Pixie\node_modules\socket.io-parser\index.js:247:12)
    at Client.ondata (C:\Work\Pixie\src\Pixie\node_modules\socket.io\lib\client.js:175:18)
    at emitOne (events.js:90:13)
```
### Enviroment Details

- Karma version (output of `0.13.22`):
- Relevant part of your `karma.config.js` file
```
        files: [
            // paths loaded by Karma
            { pattern: "node_modules/angular2/bundles/angular2-polyfills.js", included: true, watched: true },
            { pattern: "node_modules/systemjs/dist/system.src.js", included: true, watched: true },
            { pattern: "node_modules/rxjs/bundles/Rx.js", included: true, watched: true },
            { pattern: "node_modules/angular2/bundles/angular2.dev.js", included: true, watched: true },
            { pattern: "node_modules/angular2/bundles/testing.dev.js", included: true, watched: true },
            { pattern: "node_modules/angular2/bundles/http.dev.js", included: true, watched: true },
            { pattern: "node_modules/angular2/bundles/router.dev.js", included: true, watched: true },
            { pattern: "karma-test-shim.js", included: true, watched: true },

            // paths loaded via module imports
            { pattern: "wwwroot/app/**/*.js", included: false, watched: true },

            // paths to support debugging with source maps in dev tools
            { pattern: "app/**/*.ts", included: false, watched: false },
            { pattern: "wwwroot/app/**/*.js.map", included: false, watched: false }
        ],
        // test results reporter to use
        // possible values: 'dots', 'progress'
        // available reporters: https://npmjs.org/browse/keyword/karma-reporter
        reporters: ["progress", "coverage"],

        // default value
        coverageReporter:
        {
            includeAllSources: true,
            type: "json",
            dir: "coverage",
            subdir: "json",
            file: "coverage-final.json"
        },
```
### Steps to reproduce the behaviour

1. Have working tests
2. Comment out or remove content of entire test file
3. run karma

**Comment by westonpace** [comment]
The problem appears to be the way karma interacts with SystemJS.  When SystemJS encounters an error it builds an Error object.  It then appends some actually useful properties to that object (such as the original error).  However, all of these properties are non-enumerable (I think because they are not on the Error prototype).

Karma then needs to send this error across the wire to the test server (e.g. the test runner, your browser, needs to talk with the test server, a node application).  It does this over a socket using the socket.io library.  The socket.io library needs to serialize the error object from SystemJS to put on the wire.  When it serializes the object it uses json.stringify which skips non-enumerable properties.

So I'm not sure if this is a fix in SystemJS (create custom error types with all fields or add fields as enumerable), in socket.io (serialize non-enumerable properties), or in karma (somehow change the properties to enumerable or something before sending it to socket.io).

In the meantime I get around it by setting a breakpoint in my test browser instance and inspecting the error in Firebug before it gets sent across the wire.
