### ISSUE TITLE
Scripts included in html are not run on the firefox, and throw exceptions

### ISSUE THREAD

**Issue by falsandtru** [karma-runner/karma#2247]
When I run tests on chrome and firefox.
### Expected behavior

Run tests on all browsers.
### Actual behavior

Run tests only on the firefox.
### Enviroment Details
- Karma version (output of `karma --version`): 1.1.1
- Relevant part of your `karma.config.js` file

``` js
module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['mocha'],
    files: [
      { pattern: 'test/integration/usecase/**/*', watched: true, served: true, included: true }
    ],
    exclude: [
    ],
    espowerPreprocessor: {
      options: {
        emitActualCode: false,
        ignoreUpstreamSourceMap: true
      }
    },
    reporters: ['dots'],
    coverageReporter: {
      dir: 'coverage',
      subdir: function (browser, platform) {
        return browser.toLowerCase().split(' ')[0];
      },
      reporters: [
        { type: 'lcov' },
        { type: 'text-summary', subdir: '.', file: 'summary.txt' }
      ]
    },
    autoWatch: true,
    customLaunchers: {
      IE11: {
        base: 'IE',
        'x-ua-compatible': 'IE=EmulateIE11'
      }
    },
    browsers: ['Chrome', 'Firefox']
  });
};
```

``` html
<script>
  it('', function () {
  });
</script>
```
### Steps to reproduce the behaviour
1. Run tests.

```
$ gulp test
(node:17652) fs: re-evaluating native module sources is not supported. If you ar
e using the graceful-fs module, please update it to a more recent version.
[08:42:42] Using gulpfile .\gulpfile.js
[08:42:42] Starting 'clean'...
[08:42:42] Finished 'clean' after 11 ms
[08:42:42] Starting 'test'...
[08:42:42] Starting 'ts:test'...
[08:42:49] Finished 'ts:test' after 6.69 s
[08:42:49] Starting 'karma:test'...
DEPRECATED: use your own version of lodash, this will go away in karma@2.0
DEPRECATED: use your own version of lodash, this will go away in karma@2.0
11 07 2016 08:42:51.833:INFO [karma]: Karma v1.1.1 server started at http://loca
lhost:9876/
11 07 2016 08:42:51.839:INFO [launcher]: Launching browsers Chrome, Firefox with
 unlimited concurrency
11 07 2016 08:42:51.858:INFO [launcher]: Starting browser Chrome
11 07 2016 08:42:51.924:INFO [launcher]: Starting browser Firefox
11 07 2016 08:42:57.392:INFO [Chrome 51.0.2704 (Windows 7 0.0.0)]: Connected on
socket /#fCDNbqKy7qLa3MShAAAA with id 46302688
.
Chrome 51.0.2704 (Windows 7 0.0.0): Executed 1 of 1 SUCCESS (0.018 secs / 0.001
secs)
11 07 2016 08:43:09.767:INFO [Firefox 47.0.0 (Windows 7 0.0.0)]: Connected on so
cket /#mUC_0w-MNq_rOErNAAAB with id 96294767
Firefox 47.0.0 (Windows 7 0.0.0): Executed 0 of 0 ERROR (0.009 secs / 0 secs)
[08:43:11] 'karma:test' errored after 22 s
[08:43:11] Error: 1
    at formatError (C:\Users\admin\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:195:15)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (.\node_modules\orchestrator\index.js:264:8)
    at .\node_modules\orchestrator\index.js:275:23
    at finish (.\node_modules\orchestrator\lib\runTask.js:21:8)
    at cb (.\node_modules\orchestrator\lib\runTask.js:29:3)
    at removeAllListeners (.\node_modules\karma\lib\server.js:379:7)
    at Server.<anonymous> (.\node_modules\karma\lib\server.js:390:9)
    at Server.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at Server.emit (events.js:185:7)
    at emitCloseNT (net.js:1549:8)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[08:43:11] Finished 'test' after 28 s
```

**Comment by devoto13** [comment]
Unfortunately, it is not possible to tell what is going on with the information provided. I hope you have been able to figure it out by now. If not, please create a minimal reproduction where we can observe the problem and open a new issue, so we can take a look.
