### ISSUE TITLE
Karma suddenly stopped working on my system

### ISSUE THREAD

**Issue by ladvishal1985** [karma-runner/karma#2262]
### Expected behavior
karma start command should start karma and execute the unit tests.
### Actual behavior
I recieve the following errors.
```javascript 
18 07 2016 13:39:43.268:ERROR [karma]: [TypeError: Cannot read property 'replace
' of undefined]
TypeError: Cannot read property 'replace' of undefined
    at Tapable.join (webapp\node_modules\enhanced-resolve\node_modules\memory-fs\lib\join.js:11
:73)
    at Tapable.<anonymous> (webapp\node_modules\enhanced-resolve\lib\FileAppendPlugin.js:14:19)

    at Tapable.applyPluginsParallelBailResult (webapp\node_modules\tapable\lib\Tapable.js:139:1
4)
    at Tapable.<anonymous> (webapp\node_modules\enhanced-resolve\lib\Resolver.js:103:8)
    at Tapable.Resolver.forEachBail (webapp\node_modules\enhanced-resolve\lib\Resolver.js:196:3)
    at Tapable.doResolve (webapp\node_modules\enhanced-resolve\lib\Resolver.js:102:7)
    at Tapable.resolve (webapp\node_modules\enhanced-resolve\lib\Resolver.js:45:14)
    at Tapable.resolve (webapp\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:23:14)
    at webapp\node_modules\webpack\lib\NormalModuleFactory.js:169:12
    at webapp\node_modules\async\lib\async.js:356:13
    at async.forEachOf.async.eachOf (webapp\node_modules\async\lib\async.js:233:13)
    at _asyncMap (webapp\node_modules\async\lib\async.js:355:9)
    at Object.map (webapp\node_modules\async\lib\async.js:337:20)
    at NormalModuleFactory.resolveRequestArray (webpack\lib\NormalModuleFac
tory.js:166:8)
    at webapp\node_modules\async\lib\async.js:718:13
    at async.forEachOf.async.eachOf (webapp\node_modules\async\lib\async.js:233:13)```
### Enviroment Details

- Karma version (output of `karma --version`):  1.1.1
- Relevant part of your `karma.config.js` file
```javascript
var path = require('path');
var webpack = require('webpack');
module.exports = function (config) {
    config.set({
        browsers: ['Chrome'],
        singleRun: false,
        frameworks: ['mocha'],
        files: [
            'tests.webpack.js'
        ],
        preprocessors: {
            'tests.webpack.js': ['webpack']
        },
        webpack: {
            devtool: 'inline-source-map',
            module: {
                loaders: [
                    {   test: /\.(js|jsx)$/, 
                        exclude: /node_modules/,
                        loader: 'babel-loader'
                    },
                    {   test: /\.(css|scss)$/, 
                        loaders: [ 'style'| 'css?sourceMap'|'sass?sourceMap' ],
                        include: [
                            path.resolve(__dirname, "app"),
                        ]
                    }
                ]
                
            },
            watch: true,
        },
        webpackServer: {
            noInfo: true
        },
        plugins: [
          require("karma-webpack"),
          require("karma-mocha"),
          require("karma-chrome-launcher")
        ]
    });
};

package.json file contains
"devDependencies": {
    "babel": "^6.3.26",
    "babel-cli": "^6.4.5",
    "babel-core": "^6.3.26",
    "babel-eslint": "^6.1.0",
    "babel-loader": "^6.2.1",
    "babel-plugin-react-intl": "^2.0.0",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "body-parser": "^1.15.2",
    "css-loader": "^0.23.1",
    "eslint": "^2.13.1",
    "eslint-html-reporter": "^0.5.2",
    "eslint-loader": "^1.3.0",
    "eslint-plugin-react": "^5.2.2",
    "expect": "^1.14.0",
    "extract-text-webpack-plugin": "^1.0.1",
    "imports-loader": "^0.6.4",
    "json-server": "^0.8.14",
    "karma": "^1.1.1",
    "karma-chrome-launcher": "^1.0.1",
    "karma-cli": "^1.0.1",
    "karma-mocha": "^1.1.1",
    "karma-webpack": "^1.7.0",
    "mocha": "^2.5.3",
    "node-sass": "^3.3.3",
    "react-addons-perf": "^15.1.0",
    "react-addons-test-utils": "^15.1.0",
    "react-hot-loader": "^1.3.0",
    "sass-loader": "^3.0.0",
    "style-loader": "^0.13.1",
    "uglify-loader": "^1.2.0",
    "webpack": "^1.12.2",
    "webpack-bundle-size-analyzer": "^2.0.1",
    "webpack-dev-server": "^1.12.1"
  },
```
### Steps to reproduce the behavior
This issue started popping up suddenly. I installed coverage tools karma-coverage and istanbul-instrumenter-loader and it was working fine earlier.

I tried removing all the node_modules global as well as local and installing them again. But still I am unable to start karma in any case.

**Comment by ladvishal1985** [comment]
Closing this issue. I reinstalled npm packages again it works. Though it does not look like a issue with karma.
