### ISSUE TITLE
autoWatch: Unhandled rejection TypeError: other.compare is not a function

### ISSUE THREAD

**Issue by tkhyn** [karma-runner/karma#2266]
Hi there,

I noticed a bug when watching file changes with karma 1.1.1. It does not happen with 0.13.22.
I'm on Windows 7 running node 4.4.7.

Each time a file is changed, an error is raised, with the following stack trace:

```
Unhandled rejection TypeError: other.compare is not a function
    at d:\path\to\my\project\node_modules\karma\lib\file-list.js:237:28
    at Array.forEach (native)
    at d:\path\to\my\project\node_modules\karma\lib\file-list.js:235:14
    at Array.forEach (native)
    at Object.defineProperty.get (d:\path\to\my\project\node_modules\karma\lib\file-list.js:232:20)
    at d:\path\to\my\project\node_modules\karma\lib\file-list.js:205:16
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at tryCatcher (d:\path\to\my\project\node_modules\karma\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (d:\path\to\my\project\node_modules\karma\node_modules\bluebird\js\release\promise.js:504:31)
    at Promise._settlePromise (d:\path\to\my\project\node_modules\karma\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromise0 (d:\path\to\my\project\node_modules\karma\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (d:\path\to\my\project\node_modules\karma\node_modules\bluebird\js\release\promise.js:685:18)
    at Promise._fulfill (d:\path\to\my\project\node_modules\karma\node_modules\bluebird\js\release\promise.js:630:18)
    at MappingPromiseArray.PromiseArray._resolve (d:\path\to\my\project\node_modules\karma\node_modules\bluebird\js\release\promise_array.js:125:19)
    at MappingPromiseArray._promiseFulfilled (d:\path\to\my\project\node_modules\karma\node_modules\bluebird\js\release\map.js:97:18)
    at Promise._settlePromise (d:\path\to\my\project\node_modules\karma\node_modules\bluebird\js\release\promise.js:566:26)
    at Promise._settlePromise0 (d:\path\to\my\project\node_modules\karma\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (d:\path\to\my\project\node_modules\karma\node_modules\bluebird\js\release\promise.js:685:18)
    at Promise._fulfill (d:\path\to\my\project\node_modules\karma\node_modules\bluebird\js\release\promise.js:630:18)
    at Promise._resolveCallback (d:\path\to\my\project\node_modules\karma\node_modules\bluebird\js\release\promise.js:425:57)
    at Promise._settlePromiseFromHandler (d:\path\to\my\project\node_modules\karma\node_modules\bluebird\js\release\promise.js:516:17)
    at Promise._settlePromise (d:\path\to\my\project\node_modules\karma\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromise0 (d:\path\to\my\project\node_modules\karma\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (d:\path\to\my\project\node_modules\karma\node_modules\bluebird\js\release\promise.js:685:18)
    at Promise._fulfill (d:\path\to\my\project\node_modules\karma\node_modules\bluebird\js\release\promise.js:630:18)
    at MappingPromiseArray.PromiseArray._resolve (d:\path\to\my\project\node_modules\karma\node_modules\bluebird\js\release\promise_array.js:125:19)
    at MappingPromiseArray._promiseFulfilled (d:\path\to\my\project\node_modules\karma\node_modules\bluebird\js\release\map.js:97:18)
```

Steps to reproduce are pretty basic, launch a karma 1.1.1 server with ``autoWatch: true`` and change a watched file.

I tried to see what was the value of ``other`` through a ``console.log(other)`` just before ``file-list.js:237`` but it never prints the output before raising the error (it only prints ``undefined`` when the server is started), so I'm afraid I can't provide much more information on the bug than the stack trace.

I reverted to 0.13.22 and everything works fine.

Thanks in advance for looking into this.

**Comment by m-a-r-c-e-l-i-n-o** [comment]
@tkhyn A pr for this is being discussed here: https://github.com/karma-runner/karma/pull/2255

**Comment by tkhyn** [comment]
Thanks for the quick reply, I'll close this and follow the PR then.
