### ISSUE TITLE
SyntaxError: Unable to parse JSON string while running karma with Gulp

### ISSUE THREAD

**Issue by jrubstein** [karma-runner/karma#2269]
### Expected behavior

The test should passed without errors.
### Actual behavior

After the tests passed the the server throws an error.
### Enviroment Details
- Karma version: 1.1.1

Running `karma start` works perfectly however when running with the server fails.

output:

21 07 2016 16:46:11.280:INFO [karma]: Karma v1.1.1 server started at http://localhost:9876/
21 07 2016 16:46:11.283:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
21 07 2016 16:46:11.303:INFO [launcher]: Starting browser PhantomJS
21 07 2016 16:46:12.316:INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket /#kWIwBT_-ApPJn1_5AAAA with id 15293690
LOG: 'Analytics Module loaded'
PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 9 of 9 SUCCESS (7.317 secs / 0.002 secs)

=============================== Coverage summary ===============================
Statements   : 63.41% ( 260/410 ), 28 ignored
Branches     : 74.48% ( 108/145 ), 48 ignored
Functions    : 80.65% ( 75/93 ), 28 ignored
Lines        : 14.94% ( 23/154 )
LOG: 'globalHeader.min.css loaded successfully!'
LOG: 'globalHeader.min.css loaded successfully!'
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  **SyntaxError: Unable to parse JSON string
  at undefined:1**
PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 9 of 9 ERROR (7.344 secs / 0.002 secs)

Stack trace:

```
at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
at emitOne (events.js:77:13)
at Gulp.emit (events.js:169:7)
at Gulp.Orchestrator._emitTaskDone (/Users/u280285/work/src/generated/ale/ale-webapp/node_modules/orchestrator/index.js:265:8)
at /Users/u280285/work/src/generated/ale/ale-webapp/node_modules/orchestrator/index.js:276:23
at finish (/Users/u280285/work/src/generated/ale/ale-webapp/node_modules/orchestrator/lib/runTask.js:21:8)
at cb (/Users/u280285/work/src/generated/ale/ale-webapp/node_modules/orchestrator/lib/runTask.js:29:3)
at removeAllListeners (/Users/u280285/work/src/generated/ale/ale-webapp/node_modules/karma/lib/server.js:379:7)
at Server.<anonymous> (/Users/u280285/work/src/generated/ale/ale-webapp/node_modules/karma/lib/server.js:390:9)
at Server.g (events.js:260:16)
at emitNone (events.js:72:20)
at Server.emit (events.js:166:7)
at emitCloseNT (net.js:1524:8)
at nextTickCallbackWith1Arg (node.js:430:9)
at process._tickCallback (node.js:352:17)
```

Any idea how to fix it?
Thanks,
Jonathan

**Comment by wesleycho** [comment]
This sounds like a legitimate failure in the test being executed, although without a minimal reproduction/more details, we likely cannot help here.

**Comment by devoto13** [comment]
Closing as per above.
