### ISSUE TITLE
Karma fails to delete temporary files (Cannot read property 'length' of undefined)

### ISSUE THREAD

**Issue by mickaeltr** [karma-runner/karma#2325]
### Actual behavior

For unknown reasons, my karma tests started to fail with the following error:

```
[1A[2KPhantomJS 2.1.1 (Linux 0.0.0): Executed 145 of 145 SUCCESS (1.264 secs / 0.14 secs)
[31m22 08 2016 12:04:00.201:ERROR [karma]: [39m[TypeError: Cannot read property 'length' of undefined]
TypeError: Cannot read property 'length' of undefined
    at Function.glob.hasMagic (…/node_modules/karma/node_modules/glob/glob.js:106:29)
    at rimraf (…/node_modules/karma/node_modules/rimraf/rimraf.js:61:36)
    at Object.module.exports.remove (…/node_modules/karma/lib/temp_dir.js:28:5)
    at Object._clearTempDirAndReportDone (…/node_modules/karma/lib/launchers/process.js:106:13)
    at Object._onProcessExit (…/node_modules/karma/lib/launchers/process.js:102:10)
    at ChildProcess.<anonymous> (…/node_modules/karma/lib/launchers/process.js:68:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

The `pattern` sent to `glob` and that makes it fail is: `/var/folders/m2/3_c7shb51wjf9wmxnq2rfjc80000gn/T/karma-83266170`
### Environment Details
- Karma version (output of `karma --version`): 1.2.0
- Relevant part of your `karma.config.js` file

```
var ExtractTextPlugin = require("extract-text-webpack-plugin");
var webpackConfig = require("./webpack.config");

module.exports = function (config) {
  config.set({
    frameworks: ["mocha", "sinon-chai"],

    files: [
      "app/config.js",
      "app/index.js",
      "node_modules/angular-mocks/angular-mocks.js",
      "test/**/*.js"
    ],

    preprocessors: {
      "app/index.js": ["webpack"],
      "test/**/*.js": ["webpack"]
    },

    browsers: ["PhantomJS"],

    singleRun: true,

    webpack: {
      module: webpackConfig.module,
      plugins: [new ExtractTextPlugin("[hash].[name].css")]
    },

    webpackServer: {quiet: true}
  });
};
```

**Comment by kouhin** [comment]
+1

**Comment by basilfx** [comment]
Same problem here.

I have added some `console.log`'s in the `glob.hasMagic` method (where the error is thrown):

```js
glob.hasMagic = function (pattern, options_) {
  var options = extend({}, options_)
  options.noprocess = true

  console.log(pattern)    // -->> /tmp/karma-84393718
  console.log(options_)    // -->> undefined

  var g = new Glob(pattern, options)
  var set = g.minimatch.set
  if (set.length > 1)
    return true

  console.log(set)    // -->> []

  for (var j = 0; j < set[0].length; j++) {
    if (typeof set[0][j] !== 'string')
      return true
  }

  return false
}
```

Running this from the REPL, succeeds:

```js
> var glob = require('glob');
undefined
> glob.hasMagic("/tmp/karma-70836005", undefined)
false
```

**Comment by mickaeltr** [comment]
In my case, we are using Node.js 4.4.7, NPM 2.15.9 and it fails on both MacOS X and Debian 7

**Comment by artgladun** [comment]
For tests I go back with karma version to 0.13 and it works.

**Comment by TinOo512** [comment]
Same problem here also.

* Karma: 0.13.22
* Node.JS: 4.4.5
* NPM: 3.8.9

**Comment by basilfx** [comment]
@artgladun I tried to go back to 0.13.22, but that did not work for me.

I to applied https://github.com/isaacs/node-glob/pull/264, and that works for me. Verified that the directory is cleared afterwards.

**Comment by lvandergrient** [comment]
I was able to fix this problem by adding the latest version of the `glob` package (7.0.6) to my project's `devDependecies`.
