### ISSUE TITLE
config.frameworks.forEach is not a function in karma server

### ISSUE THREAD

**Issue by ivanhdzd** [karma-runner/karma#2343]
## When try to run karma test by npm, terminal show it:

```
$ npm test

> angular-testing-tutorial@1.0.0 test C:\Users\Lion\Documents\Angular\AngularJS-Testing
> karma start karma.conf.js

C:\Users\Lion\Documents\Angular\AngularJS-Testing\node_modules\karma\lib\server.js:142
  config.frameworks.forEach(function (framework) {
                    ^

TypeError: config.frameworks.forEach is not a function
    at Server._start (C:\Users\Lion\Documents\Angular\AngularJS-Testing\node_modules\karma\lib\server.js:142:21)
    at invoke (C:\Users\Lion\Documents\Angular\AngularJS-Testing\node_modules\di\lib\injector.js:75:15)
    at Server.start (C:\Users\Lion\Documents\Angular\AngularJS-Testing\node_modules\karma\lib\server.js:103:18)
    at Object.exports.run (C:\Users\Lion\Documents\Angular\AngularJS-Testing\node_modules\karma\lib\cli.js:266:26)
    at Object.<anonymous> (C:\Users\Lion\Documents\Angular\AngularJS-Testing\node_modules\karma\bin\karma:3:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
npm ERR! Test failed.  See above for more details.

```

### I had been following this tutorial: [AngularJS Tests Unitarios](https://www.adictosaltrabajo.com/tutoriales/angularjs-test-unitarios/)

- Karma version `1.2.0`:

### package.json
```
{
  "name": "angular-testing-tutorial",
  "version": "1.0.0",
  "description": "AngularJS",
  "scripts": {
    "start": "gulp && gulp browser-sync",
    "postinstall": "bower install",
    "test": "karma start karma.conf.js"
  },
  "dependencies": {
    "browser-sync": "^2.14.0",
    "express": "^4.14.0",
    "gulp": "^3.9.1",
    "gulp-load-plugins": "^1.2.4",
    "gulp-notify": "^2.2.0",
    "gulp-rename": "^1.2.2",
    "wiredep": "^4.0.0"
  },
  "devDependencies": {
    "karma": "^1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-firefox-launcher": "^1.0.0",
    "karma-jasmine": "^1.0.2"
  }
}
```

### karma.conf.js

```
module.exports = function(config) {
	config.set({
		basePath: './',
		files: [
			'app/bower_components/angular/angular.js',
			'app/bower_components/angular-mocks/angular-mocks.js',
			'app/angular/**/*.js',
			'tests/**/*.js'
		],
		autoWatch: false,
		frameworks: 'jasmine',
		browsers: ['Chrome', 'Firefox'],
		singleRun: true,
		plugins: [
			require('karma-chrome-launcher'),
			require('karma-firefox-launcher'),
			require('karma-jasmine')
		]
	});
}
```

### tests/filters/uppercase_test.js
```
describe('App module', function() {
	beforeEach(angular.mock.module('App'));

	describe('Uppercase filter', function() {
		it ('It must change to uppercase whatever string and unshift asterisks.',
			inject(function(UppercaseFilter) {
				var input = 'someThing';
				var expectedOutput = '**SOMETHING';
				expect(uppercaseFilter(input)).toEqual(expectedOutput);
			});
		);
	});
});
```

**Comment by ivanhdzd** [comment]
Sorry for this issue, my error was inside **karma.conf.js**
I change `frameworks: 'jasmine',` for `frameworks: ['jasmine'],`
