### ISSUE TITLE
Error: No provider for "framework:chai"!

### ISSUE THREAD

**Issue by joetidee** [karma-runner/karma#2550]
Have loaded chai 3.5.0 package into my webpack project as a dependency, am getitng the following error when running `sudo npm run test`:

```
Error: No provider for "framework:chai"! (Resolving: framework:chai)
    at error (/tidee/auth_app/node_modules/di/lib/injector.js:22:12)
    at Object.get (/tidee/auth_app/node_modules/di/lib/injector.js:9:13)
    at Injector.get (/tidee/auth_app/node_modules/di/lib/injector.js:54:19)
    at /tidee/auth_app/node_modules/karma/lib/server.js:143:20
    at Array.forEach (native)
    at Server._start (/tidee/auth_app/node_modules/karma/lib/server.js:142:21)
    at Injector.invoke (/tidee/auth_app/node_modules/di/lib/injector.js:75:15)
    at Server.start (/tidee/auth_app/node_modules/karma/lib/server.js:103:18)
    at Object.exports.run (/tidee/auth_app/node_modules/karma/lib/cli.js:280:26)
    at Object.<anonymous> (/tidee/auth_app/node_modules/karma/bin/karma:3:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
```

karma.conf.js:
```

module.exports = function karmaConfig(config){
    config.set({
        frameworks: ['mocha','chai'],
        reporters: ['spec','coverage'],
        files: [
            'node_modules/phantomjs-polyfill/bind-polyfill.js',
            'tests/**/*_test.*'
        ],
        preprocessors: {
            'tests/**/*_test.*': ['webpack','sourcemap']
        },
        browsers: [
            'PhantomJS'
        ],
        singleRun: true,
        autoWatch: true,
        coverageReporter: {
            dir: 'client/dist/coverage/',
            type: 'html'
        },
        webpack: require('./webpack.config.js'),
        webpackMiddleware: {
            noInfo: true
        }
    });
};
```

**Comment by joetidee** [comment]
Installed the `karma-chai` package to fix this.
