### ISSUE TITLE
EINVAL error on 'karma init'

### ISSUE THREAD

**Issue by devinscodev** [karma-runner/karma#2579]
### Command
`C:\Development\Proj1> karma init karma.conf.js`

### Expected behaviour
The Karma init questionnaire should begin 

### Actual behaviour
I get this error:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EINVAL
    at exports._errnoException (util.js:1022:11)
    at WriteStream.Socket._writeGeneric (net.js:715:26)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at Interface._writeToOutput (readline.js:256:17)
    at Interface._insertString (readline.js:406:12)
    at Interface._ttyWrite (readline.js:933:18)
    at Interface.write (readline.js:352:24)
    at StateMachine.nextQuestion (C:\Development\Proj1\node_modules\karma\lib\init\state_machine.js:111:11)
    at StateMachine.process (C:\Development\Proj1\node_modules\karma\lib\init\state_machine.js:135:10)
    at Object.exports.init (C:\Development\Proj1\node_modules\karma\lib\init.js:238:6)
    at Object.exports.run (C:\Development\Proj1\node_modules\karma\lib\cli.js:289:25)
    at requireCliAndRun (C:\Users\User1\AppData\Roaming\npm\node_modules\karma-cli\bin\karma:44:16)
```

### Environment Details
- OS: Windows 10
- Karma version: 1.4.1
- Node version: 7.1.0

I have tried this both by invoking Karma directly through `./node_modules/.bin/karma init karma.conf.js` and by installing the cli and invoking `karma init karma.conf.js`. Both commands yield the same error.

**Comment by devinscodev** [comment]
Looks like this is an issue (nodejs/node#9542) with the version of Node and Windows I was using. I have switched back to 6.9.5 and am no longer experiencing the issue.
