### ISSUE TITLE
Error: Cannot find module 'jasmine-core'

### ISSUE THREAD

**Issue by ORESoftware** [karma-runner/karma#2804]
After running

```bash
npm install -g karma && npm install karma --save-dev
```

when I run:

`karma start`

I get:

```
Error: Cannot find module 'jasmine-core'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.resolve (internal/module.js:27:19)
    at initJasmine (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/karma-jasmine/lib/index.js:8:42)
    at Array.invoke (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/di/lib/injector.js:75:15)
    at Injector.get (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/di/lib/injector.js:48:43)
    at /Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/karma/lib/server.js:143:20

```

**Comment by ORESoftware** [comment]
nevermind, sorry, I didn't see these instructions in the tutorial:

`npm install karma karma-jasmine jasmine-core karma-chrome-launcher --save-dev`
