### ISSUE TITLE
Error when run angular2 tests

### ISSUE THREAD

**Issue by alvindaiyan** [karma-runner/karma#2806]
### Actual behaviour
I got error as follows:
```
Can not load "webpack"!
  TypeError: Cannot read property 'plugin' of undefined
    at PathsPlugin.apply (/Users/yan/Dev/work/marriages-ng/node_modules/@ngtools/webpack/src/paths-plugin.js:75:18)
    at Resolver.apply (/Users/yan/Dev/work/marriages-ng/node_modules/tapable/lib/Tapable.js:375:16)
    at /Users/yan/Dev/work/marriages-ng/node_modules/enhanced-resolve/lib/ResolverFactory.js:249:12
    at Array.forEach (native)
    at Object.exports.createResolver (/Users/yan/Dev/work/marriages-ng/node_modules/enhanced-resolve/lib/ResolverFactory.js:248:10)
    at WebpackOptionsApply.process (/Users/yan/Dev/work/marriages-ng/node_modules/webpack/lib/WebpackOptionsApply.js:283:46)
    at webpack (/Users/yan/Dev/work/marriages-ng/node_modules/webpack/lib/webpack.js:36:48)
    at new Plugin (/Users/yan/Dev/work/marriages-ng/node_modules/karma-webpack/lib/karma-webpack.js:63:18)
    at invoke (/Users/yan/Dev/work/marriages-ng/node_modules/di/lib/injector.js:75:15)
    at Array.instantiate (/Users/yan/Dev/work/marriages-ng/node_modules/di/lib/injector.js:59:20)
    at get (/Users/yan/Dev/work/marriages-ng/node_modules/di/lib/injector.js:48:43)
    at /Users/yan/Dev/work/marriages-ng/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
    at Array.invoke (/Users/yan/Dev/work/marriages-ng/node_modules/di/lib/injector.js:70:31)
    at Injector.get (/Users/yan/Dev/work/marriages-ng/node_modules/di/lib/injector.js:48:43)
    at instantiatePreprocessor (/Users/yan/Dev/work/marriages-ng/node_modules/karma/lib/preprocessor.js:55:20)
    at /Users/yan/Dev/work/marriages-ng/node_modules/karma/lib/preprocessor.js:106:17
    at Array.forEach (native)
    at /Users/yan/Dev/work/marriages-ng/node_modules/karma/lib/preprocessor.js:103:27
    at module.exports (/Users/yan/Dev/work/marriages-ng/node_modules/karma/node_modules/isbinaryfile/index.js:28:12)
    at /Users/yan/Dev/work/marriages-ng/node_modules/karma/lib/preprocessor.js:84:7
    at /Users/yan/Dev/work/marriages-ng/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
```

### Environment Details

- Karma version (output of `karma --version`):
"karma": "1.2.0",

- Relevant part of your `karma.config.js` file
// Karma configuration file, see link for more information
// https://karma-runner.github.io/0.13/config/configuration-file.html
```
module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', 'angular-cli'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-phantomjs-launcher'),
      require('karma-remap-istanbul'),
      require('karma-spec-reporter'),
      require('angular-cli/plugins/karma')
    ],
    files: [
      { pattern: './src/test.ts', watched: false }
    ],
    preprocessors: {
      './src/test.ts': ['angular-cli']
    },
    mime: {
      'text/x-typescript': ['ts','tsx']
    },
    remapIstanbulReporter: {
      reports: {
        html: 'coverage',
        lcovonly: './coverage/coverage.lcov'
      }
    },
    angularCli: {
      config: './angular-cli.json',
      environment: 'dev'
    },
    reporters: config.angularCli && config.angularCli.codeCoverage
          ? ['spec', 'karma-remap-istanbul']
          : ['spec'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['PhantomJS'],
    singleRun: false,
    browserNoActivityTimeout: 100000,
    browserDisconnectTolerance: 2
  });
};
```

**Comment by alvindaiyan** [comment]
I think it's @ngtools problem. @ngtools 1.6.0, it's not compatible to the current webpack used in angular project.
