### ISSUE TITLE
 TypeError: vm.$el.querySelector is not a function

### ISSUE THREAD

**Issue by fjy5314** [karma-runner/karma#2830]
```
> xxxxxx@1.0.0 unit C:\Users\flny\Desktop\新建文件夹\xxxxxx
> cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run

20 09 2017 09:51:39.954:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
20 09 2017 09:51:39.963:INFO [launcher]: Launching browser Chrome with unlimited concurrenc

20 09 2017 09:51:39.987:INFO [launcher]: Starting browser Chrome
20 09 2017 09:51:43.090:INFO [Chrome 60.0.3112 (Windows 7 0.0.0)]: Connected on socket EWR3
4CGWgI1y0CzxAAAA with id 59744408
INFO LOG: 'Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools'

  Hello.vue
    √ should render correct contents
ERROR LOG: '[Vue warn]: Error in getter for watcher "loginNum": "TypeError: Cannot read pro
perty 'state' of undefined"

(found in <Root>)'
ERROR LOG: TypeError{}
ERROR LOG: '[Vue warn]: Error in render function: "TypeError: Cannot read property 'state'
of undefined"

(found in <Root>)'
ERROR LOG: TypeError{}
ERROR LOG: '[Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'state' of
undefined"

(found in <Root>)'
ERROR LOG: TypeError{}

  Login.vue
    × 登陆
        TypeError: vm.$el.querySelector is not a function
            at Context.<anonymous> (webpack:///test/unit/specs/Login.spec.js:15:18 <- index
.js:44684:19)


Chrome 60.0.3112 (Windows 7 0.0.0): Executed 2 of 2 (1 FAILED) (0.893 secs / 0.053 secs)
TOTAL: 1 FAILED, 1 SUCCESS


1) 登陆
     Login.vue
     TypeError: vm.$el.querySelector is not a function
    at Context.<anonymous> (webpack:///test/unit/specs/Login.spec.js:15:18 <- index.js:4468
4:19)



=============================== Coverage summary ===============================
Statements   : 1.93% ( 18/934 )
Branches     : 0% ( 0/222 )
Functions    : 0.58% ( 1/173 )
Lines        : 1.93% ( 18/934 )
================================================================================

npm ERR! Windows_NT 6.1.7600
npm ERR! argv "E:\\nodejs\\node.exe" "E:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run"
 "unit"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! xxxxxx@1.0.0 unit: `cross-env BABEL_ENV=test karma start test/unit/karma.conf.js -
-single-run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xxxxxx@1.0.0 unit script 'cross-env BABEL_ENV=test karma start test/
unit/karma.conf.js --single-run'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the xxxxxx package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs xxxxxx
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls xxxxxx
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\flny\Desktop\新建文件夹\xxxxxx\npm-debug.log

npm ERR! Windows_NT 6.1.7600
npm ERR! argv "E:\\nodejs\\node.exe" "E:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run"
 "test"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! xxxxxx@1.0.0 test: `npm run unit`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xxxxxx@1.0.0 test script 'npm run unit'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the xxxxxx package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run unit
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs xxxxxx
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls xxxxxx
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\flny\Desktop\新建文件夹\xxxxxx\npm-debug.log
```

karma.config
```javascript
config.set({
    // to run in additional browsers:
    // 1. install corresponding karma launcher
    //    http://karma-runner.github.io/0.13/config/browsers.html
    // 2. add it to the `browsers` array below.
    browsers: ['Chrome'],
    frameworks: ['mocha', 'sinon-chai', 'phantomjs-shim'],
    reporters: ['spec', 'coverage'],
    files: ['./index.js'],
    preprocessors: {
      './index.js': ['webpack', 'sourcemap']
    },
    webpack: webpackConfig,
    webpackMiddleware: {
      noInfo: true
    },
    coverageReporter: {
      dir: './coverage',
      reporters: [
        { type: 'lcov', subdir: '.' },
        { type: 'text-summary' }
      ]
    }
```

**Comment by EzraBrooks** [comment]
A similar issue was opened on the Webpack Vue template repository [here](https://github.com/vuejs-templates/webpack/issues/851), and appears to have been solved. Please take a look at the solution there.
