### ISSUE TITLE
master branch fails: stringify should serialize proxied functions FAILED

### ISSUE THREAD

**Issue by johnjbarton** [karma-runner/karma#2942]
### Expected behaviour
git pull master ...
npm test
pass
### Actual behaviour
Chrome 66.0.3355 (Mac OS X 10.13.3) stringify should serialize proxied functions FAILED
	AssertionError: 'function () { ... }' deepEqual 'Proxy(function abc(...) { ... })'
	    at Context.<anonymous> (absolute/var/folders/00/137s0000h01000cxqpysvccm004cz4/T/b709b7186f05f556af69d7c1a8666b16.browserify?2f2568776166a6bb8470c50f8d0112fb2cb53645:20463:14)
........
Chrome 66.0.3355 (Mac OS X 10.13.3): Executed 36 of 36 (1 FAILED) (0.12 secs / 0.031 secs)
Error
    at callDone (/work/karma/node_modules/grunt/node_modules/grunt-legacy-util/index.js:159:52)
    at ChildProcess.<anonymous> (/work/karma/node_modules/grunt/node_modules/grunt-legacy-util/index.js:198:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)

Fatal error: Client unit tests failed.
npm ERR! Test failed.  See above for more details.

### Environment Details

- Karma version (output of `karma --version`):
- Relevant part of your `karma.config.js` file

### Steps to reproduce the behaviour

1. npm test
2.
3.

**Comment by johnjbarton** [comment]
Maybe related: 
https://www.chromestatus.com/feature/5666372071718912
Function.prototype.toString revision
