### ISSUE TITLE
Karma 3.0 depends on log4js 3.x which caused a breaking change

### ISSUE THREAD

**Issue by pmazak** [karma-runner/karma#3111]
### Expected behaviour
```
> Task :proj:karmaRun 
10 08 2018 10:37:56.020:DEBUG [config]: Loading config /build/karma.conf.js
10 08 2018 10:37:56.029:DEBUG [config]: autoWatch set to false, because of singleRun
```

### Actual behaviour
```
node_modules/karma/node_modules/log4js/lib/layouts.js:69
  ) + util.format(...loggingEvent.data);
                  ^^^
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (node_modules/karma/node_modules/log4js/lib/log4js.js:27:17)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (node_modules/karma/lib/logger.js:7:14)
    at Module._compile (module.js:435:26)
```

### Environment Details
Running with gradle.plugin.com.craigburke.gradle:karma-gradle:1.4.4

### Steps to reproduce the behaviour
1.  ./gradlew karmaRun

### My workaround
```
apply plugin: "com.craigburke.karma"
karma {
    dependencies([
        // Needed because karma 3.x depended on log4js 3.x which had a breaking change.
        // It was in log4js/lib/layouts.js:69 with util.format(...loggingEvent.data)
        "karma@2.0.5"
    ])
}
```

**Comment by johnjbarton** [comment]
You will need to fix your own code for breaking changes, sorry.

**Comment by czeidler** [comment]
What do you mean by fix your own code? What is the cause of this error? thanks!

**Comment by devoto13** [comment]
@czeidler The cause is use of Node.js < 6, which is neither supported by [Karma 3+](https://github.com/karma-runner/karma/blob/master/package.json#L462), nor [log4js 3+](https://github.com/log4js-node/log4js-node/blob/master/package.json#L28).
