### ISSUE TITLE
ERROR [karma]: TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by CHBaker** [karma-runner/karma#3118]
### Expected behaviour
Run the karma test server without crashing

### Actual behaviour
karma server crashes after running boiler plate tests:
```
4 08 2018 16:01:06.067:ERROR [karma]: TypeError: Cannot read property 'push' of undefined
    at eventReporter.BaseReporter.onBrowserStart (/home/vmuser/dev/SpiritGui/node_modules/karma/lib/reporters/base.js:34:20)
    at Server.<anonymous> (/home/vmuser/dev/SpiritGui/node_modules/karma/lib/events.js:40:26)
    at emitTwo (events.js:131:20)
    at Server.emit (events.js:214:7)
    at Browser.onStart (/home/vmuser/dev/SpiritGui/node_modules/karma/lib/browser.js:123:18)
    at Socket.socket.on (/home/vmuser/dev/SpiritGui/node_modules/karma/lib/browser.js:269:39)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at /home/vmuser/dev/SpiritGui/node_modules/socket.io/lib/socket.js:528:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

```
### Environment Details

```
"dependencies": {
    "@angular/animations": "^6.1.0",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^6.1.0",
    "@ngrx/schematics": "^6.1.0",
    "@ngrx/store": "^6.1.0",
    "core-js": "^2.5.4",
    "rxjs": "^6.2.2",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.7.0",
    "@angular/cli": "~6.1.3",
    "@angular/compiler-cli": "^6.1.0",
    "@angular/language-service": "^6.1.0",
    "@ngrx/store-devtools": "^6.1.0",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~10.9.1",
    "codelyzer": "~4.4.4",
    "jasmine-core": "~3.2.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^1.3.1",
    "protractor": "^5.4.0",
    "ts-node": "~7.0.1",
    "tslint": "~5.11.0",
    "typescript": "~3.0.1"
  }
```
```
// Karma configuration file, see link for more information
// https://karma-runner.github.io/1.0/config/configuration-file.html

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular-devkit/build-angular/plugins/karma')
    ],
    client: {
      captureConsole: true,
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    coverageIstanbulReporter: {
      dir: require('path').join(__dirname, '../coverage'),
      reports: ['html', 'lcovonly'],
      fixWebpackSourcePaths: true
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false
  });
};
```

### Steps to reproduce the behaviour

1. npm install deps
2. ng test
3. open browser

**Comment by johnjbarton** [comment]
Please set `logLevel: config.LOG_DEBUG`, and post anything suspicious (check the log for redaction).

**Comment by johnjbarton** [comment]
Note the final configuration in the log, sometimes its not what we expect.

**Comment by CHBaker** [comment]
@johnjbarton hm, I'm only getting "serving cached" in the terminal, where can I find redacted logs?

**Comment by johnjbarton** [comment]
Sorry I don't know the details of your command env, maybe that `ng` thing is involved.

**Comment by CHBaker** [comment]
I'm using the Angular CLI to run the tests, when I use `LOG_DEBUG` it runs fine though

**Comment by johnjbarton** [comment]
This does not seem like something we can fix.

**Comment by drzraf** [comment]
Related stacktrace?
```
16 09 2020 11:35:38.234:WARN [karma]: Error during refresh file list. TypeError: Cannot read property 'push' of undefined
    at _reporters.forEach (/x/node_modules/karma/lib/reporters/multi.js:11:61)
    at Array.forEach (<anonymous>)
    at MultiReporter.addAdapter (/x/node_modules/karma/lib/reporters/multi.js:11:21)
    at Server.<anonymous> (/x/node_modules/karma/lib/middleware/runner.js:97:18)
    at Object.onceWrapper (events.js:286:20)
    at Server.emit (events.js:203:15)
    at Server.EventEmitter.emit (domain.js:448:20)
    at Executor.schedule (/x/node_modules/karma/lib/executor.js:31:20)
    at refreshFileList.then (/x/node_modules/karma/lib/middleware/runner.js:42:18)
```
