### ISSUE TITLE
 SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by sindhu-pradeep** [karma-runner/karma#3141]
Running Karma tests

- Karma version (output of `karma --version`):Karma version: 2.0.5

- Relevant part of your `karma.config.js` file

1. run tests individually using Karma plugin
2.25 09 2018 08:39:07.216:DEBUG [plugin]: Loading plugin karma-junit-reporter.
25 09 2018 08:39:07.262:DEBUG [plugin]: Loading plugin karma-chrome-launcher.
25 09 2018 08:39:07.282:DEBUG [plugin]: Loading plugin karma-phantomjs-launcher.
25 09 2018 08:39:07.322:DEBUG [plugin]: Loading plugin karma-jasmine.
25 09 2018 08:39:07.322:DEBUG [plugin]: Loading plugin karma-ng-html2js-preprocessor.
25 09 2018 08:39:07.322:DEBUG [plugin]: Loading plugin karma-mocha-reporter.
25 09 2018 08:39:07.353:DEBUG [plugin]: Loading plugin karma-coverage.
25 09 2018 08:39:07.920:DEBUG [plugin]: Loading plugin C:\Users\lsindhura\.IntelliJIdea2018.2\config\plugins\js-karma\js_reporter\karma-intellij\lib\intellijPlugin.js.
25 09 2018 08:39:07.938:DEBUG [web-server]: Instantiating middleware
25 09 2018 08:39:07.939:DEBUG [reporter]: Trying to load reporter: mocha
25 09 2018 08:39:07.941:DEBUG [reporter]: Trying to load color-version of reporter: mocha (mocha_color)
25 09 2018 08:39:07.941:DEBUG [reporter]: Couldn't load color-version.
25 09 2018 08:39:07.941:DEBUG [reporter]: Trying to load reporter: junit
25 09 2018 08:39:07.942:DEBUG [reporter]: Trying to load color-version of reporter: junit (junit_color)
25 09 2018 08:39:07.942:DEBUG [reporter]: Couldn't load color-version.
25 09 2018 08:39:07.943:DEBUG [reporter]: Trying to load reporter: intellij_c831a91b03572bad3b3db88354641e3b
25 09 2018 08:39:07.945:ERROR [reporter]: Can not load "intellij_c831a91b03572bad3b3db88354641e3b"!
 SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at new IntellijReporter (C:\Users\lsindhura\.IntelliJIdea2018.2\config\plugins\js-karma\js_reporter\karma-intellij\lib\intellijReporter.js:123:3)
    at invoke (C:\Users\lsindhura\workspace\my-plates\node_modules\karma\node_modules\di\lib\injector.js:75:15)
    at Array.instantiate (C:\Users\lsindhura\workspace\my-plates\node_modules\karma\node_modules\di\lib\injector.js:59:20)
    at get (C:\Users\lsindhura\workspace\my-plates\node_modules\karma\node_modules\di\lib\injector.js:48:43)
    at C:\Users\lsindhura\workspace\my-plates\node_modules\karma\lib\reporter.js:106:75
    at Array.forEach (native)
    at createReporters (C:\Users\lsindhura\workspace\my-plates\node_modules\karma\lib\reporter.js:88:9)
    at Array.invoke (C:\Users\lsindhura\workspace\my-plates\node_modules\karma\node_modules\di\lib\injector.js:75:15)
    at get (C:\Users\lsindhura\workspace\my-plates\node_modules\karma\node_modules\di\lib\injector.js:48:43)

**Comment by johnjbarton** [comment]
Looks like this is related to karma-intellij\lib\intellijReporter.js or perhaps the version of nodejs. Not something karma-runner can fix, sorry.
