### ISSUE TITLE
Karma not working with Typescript 3.2.2

### ISSUE THREAD

**Issue by KirillMetrik** [karma-runner/karma#3235]
### Expected behaviour
`npm test` compiles TS spec files and runs tests.

### Actual behaviour
The following error in console after starting
```
17 12 2018 11:18:53.227:INFO [compiler.karma-typescript]: Compiling project using Typescript 3.2.2
17 12 2018 11:18:57.443:ERROR [karma-server]: TypeError: Cannot read property 'kind' of undefined
    at checkNestedBlockScopedBinding (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:45885:48)
    at checkIdentifier (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:45791:13)
    at checkExpressionWorker (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:51773:28)
    at checkExpression (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:51745:42)
    at checkNonNullExpression (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:48096:37)
    at checkPropertyAccessExpressionOrQualifiedName (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:48129:28)
    at checkPropertyAccessExpression (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:48122:20)
    at checkExpressionWorker (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:51802:28)
    at checkExpression (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:51745:42)
    at checkNonNullExpression (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:48096:37)
    at checkPropertyAccessExpressionOrQualifiedName (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:48129:28)
    at checkPropertyAccessExpression (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:48122:20)
    at checkExpressionWorker (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:51802:28)
    at checkExpression (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:51745:42)
    at checkNonNullExpression (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:48096:37)
    at resolveCallExpression (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:49422:28)
npm ERR! Test failed.  See above for more details.
```

### Environment Details

- Karma version (output of `karma --version`): 3.1.3 (but also happens with earlier versions after upgrade to TypeScript 3.2.2)
- Relevant part of your `karma.config.js` file:
```
module.exports = function(config) {
    config.set({
        basePath: '../',
        frameworks: ['jasmine', 'karma-typescript'],
        preprocessors: {
            '**/*.ts': ['karma-typescript', 'coverage']
        },
        reporters: ['teamcity', 'coverage'],
        coverageReporter: {
            dir : 'coverage/',
            reporters: [
                {type: 'html', subdir: 'html'},
                {type: 'text-summary'}
            ],
            instrumenterOptions: {
                istanbul: { noCompact: true }
            }
        },
        karmaTypescriptConfig: {
            tsconfig: './tsconfig.json'
        },
        colors: true,
        logLevel: config.LOG_INFO,
        autoWatch: true,
        browsers: ['Chrome'],
        browserNoActivityTimeout: 100000,
        browserDisconnectTimeout: 10000,
        singleRun: true
    });
};

```

### Steps to reproduce the behaviour

1. Install TypeScript 3.2.2
2. Run `npm test` for your typescript project

**Comment by johnjbarton** [comment]
> TypeError: Cannot read property 'kind' of undefined
    at checkNestedBlockScopedBinding (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:45885:48)

This is a typescript error.
