### ISSUE TITLE
Cant run karma in Docker

### ISSUE THREAD

**Issue by georgkrause** [karma-runner/karma#3237]
### Expected behaviour

I can run `karma start` on my local machine without any issues. So I expect if I run exactly the same in a Docker Container I am able to run all the tests. 

### Actual behaviour

It exists, without any useful information:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'test' ]
2 info using npm@6.4.1
3 info using node@v10.12.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle saltui@1.0.0~pretest: saltui@1.0.0
6 info lifecycle saltui@1.0.0~test: saltui@1.0.0
7 verbose lifecycle saltui@1.0.0~test: unsafe-perm in lifecycle true
8 verbose lifecycle saltui@1.0.0~test: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/saltui-frontend/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle saltui@1.0.0~test: CWD: /root/saltui-frontend
10 silly lifecycle saltui@1.0.0~test: Args: [ '-c', './node_modules/karma/bin/karma start karma.conf.js' ]
11 silly lifecycle saltui@1.0.0~test: Returned: code: 1  signal: null
12 info lifecycle saltui@1.0.0~test: Failed to exec test script
13 verbose stack Error: saltui@1.0.0 test: `./node_modules/karma/bin/karma start karma.conf.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid saltui@1.0.0
15 verbose cwd /root/saltui-frontend
16 verbose Linux 4.19.6-1-MANJARO
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test"
18 verbose node v10.12.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error saltui@1.0.0 test: `./node_modules/karma/bin/karma start karma.conf.js`
22 error Exit status 1
23 error Failed at the saltui@1.0.0 test script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

### Environment Details

- Karma version (output of `karma --version`): 3.1.3
- Relevant part of your `karma.config.js` file

### Steps to reproduce the behaviour

1. run `karma start` in docker container

Any hints are welcome.

**Comment by johnjbarton** [comment]
The most likely explanation is that your container did not contain karma-runner.
