### ISSUE TITLE
How to solve this problem!When I launch chrome with karma

### ISSUE THREAD

**Issue by hgcoder** [karma-runner/karma#3240]
ERROR [karma-server]: { Error: spawn UNKNOWN
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at spawnWithoutOutput (E:\gulp-builder\node_modules\karma\lib\launc
ess.js:166:26)
    at Object.ProcessLauncher._execCommand (E:\gulp-builder\node_module
ib\launchers\process.js:75:21)
    at Object.ProcessLauncher._start (E:\gulp-builder\node_modules\karm
nchers\process.js:33:10)
    at Object.<anonymous> (E:\gulp-builder\node_modules\karma\lib\launc
ess.js:19:10)
    at emitOne (events.js:121:20)
    at Object.emit (events.js:211:7)
    at Object.BaseLauncher.start (E:\gulp-builder\node_modules\karma\li
rs\base.js:43:10)
    at Object.jobs.add [as j] (E:\gulp-builder\node_modules\karma\lib\l
s:85:17)
    at Object.setTimeout.bind.j (E:\gulp-builder\node_modules\qjobs\qjo
:18)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5) code: 'UNKNOWN', errno: 'U
syscall: 'spawn' }

**Comment by johnjbarton** [comment]
Looks like karma-runner is trying to launch a browser and the browser command is failing.  But this one unclearly formatted call stack is not enough.  Try the instructions here:
https://github.com/karma-runner/karma/blob/2682bff15888cd88cc7e97be2e276cf1cb7f39be/docs/intro/05-troubleshooting.md

**Comment by AlexKirilov** [comment]
Hi, there I have a similar issue, after updating angular from 11 to 12 version.

ng t
⠋ Generating browser application bundles (phase: setup)...'karma-coverage-istanbul-report
Please install 'karma-coverage' and update 'karma.conf.js.' For more info, see https://gi
Compiling @angular/cdk/keycodes : es2015 as esm2015
Compiling @angular/core : es2015 as esm2015
Compiling @angular/animations : es2015 as esm2015
Compiling @angular/compiler/testing : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/cdk/observers : es2015 as esm2015
Compiling @angular/cdk/collections : es2015 as esm2015
Compiling @angular/animations/browser : es2015 as esm2015
Compiling @angular/cdk/platform : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/cdk/bidi : es2015 as esm2015
Compiling @angular/cdk/a11y : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/cdk/scrolling : es2015 as esm2015
Compiling @angular/platform-browser/animations : es2015 as esm2015
Compiling @angular/cdk/portal : es2015 as esm2015
Compiling @angular/cdk/layout : es2015 as esm2015
Compiling @angular/common/http : es2015 as esm2015
Compiling @angular/material/core : es2015 as esm2015
Compiling @angular/cdk/overlay : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
Compiling @angular/core/testing : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling @angular/material/form-field : es2015 as esm2015
Compiling @angular/material/button : es2015 as esm2015
Compiling @angular/material/tooltip : es2015 as esm2015
Compiling @angular/material/select : es2015 as esm2015
Compiling @angular/platform-browser/testing : es2015 as esm2015
Compiling @ngrx/store : es2015 as esm2015
Compiling @angular/cdk/table : es2015 as esm2015
Compiling @angular/material/sort : es2015 as esm2015
Compiling @angular/common/testing : es2015 as esm2015
Compiling @angular/material/paginator : es2015 as esm2015
Compiling @angular/cdk/text-field : es2015 as esm2015
Compiling @angular/platform-browser-dynamic/testing : es2015 as esm2015
Compiling @angular/material/dialog : es2015 as esm2015
Compiling @angular/material/snack-bar : es2015 as esm2015
Compiling @angular/material/bottom-sheet : es2015 as esm2015
Compiling @ngrx/effects : es2015 as esm2015
Compiling @angular/material/icon : es2015 as esm2015
Compiling @auth0/auth0-angular : es2015 as esm2015
Compiling @angular/material/menu : es2015 as esm2015
Compiling @angular/material/table : es2015 as esm2015
Compiling @angular/router/testing : es2015 as esm2015
Compiling @angular/material/autocomplete : es2015 as esm2015
Compiling @angular/material/input : es2015 as esm2015
Compiling @angular/cdk/drag-drop : es2015 as esm2015
Compiling @angular/common/http/testing : es2015 as esm2015
ma\lib\launchers\process.js:33:10)
    at Object.<anonymous> (C:\FSL Source\portfolio.frontend-2\node_modules\karma\lib\launchers\process.js:19:10)
    at Object.emit (events.js:327:22)
    at Object.EventEmitter.emit (domain.js:467:12)
    at Object.BaseLauncher.start (C:\FSL Source\portfolio.frontend-2\node_modules\karma\lib\launchers\base.js:52:10)
    at Object.j (C:\FSL Source\portfolio.frontend-2\node_modules\karma\lib\launcher.js:108:17)
09 06 2021 16:36:13.678:ERROR [karma-server]: Error: spawn EPERM
    at ChildProcess.spawn (internal/child_process.js:403:11)
    at spawn (child_process.js:553:9)
    at spawnWithoutOutput (C:\FSL Source\portfolio.frontend-2\node_modules\karma\lib\launchers\process.js:174:26)
    at Object.ProcessLauncher._execCommand (C:\FSL Source\portfolio.frontend-2\node_modules\karma\lib\launchers\process.js:75:21)
    at Object.ProcessLauncher._start (C:\FSL Source\portfolio.frontend-2\node_modules\karma\lib\launchers\process.js:33:10)
    at Object.<anonymous> (C:\FSL Source\portfolio.frontend-2\node_modules\karma\lib\launchers\process.js:19:10)
    at Object.emit (events.js:327:22)
    at Object.EventEmitter.emit (domain.js:467:12)
    at Object.BaseLauncher.start (C:\FSL Source\portfolio.frontend-2\node_modules\karma\lib\launchers\base.js:52:10)
    at Object.j (C:\FSL Source\portfolio.frontend-2\node_modules\karma\lib\launcher.js:108:17) {
  errno: -4048,
  code: 'EPERM',
  syscall: 'spawn'
}

**Comment by AlexKirilov** [comment]
I found the solution to my issue. The correct combination of karma versions.
![image](https://user-images.githubusercontent.com/5669746/121493425-bced1780-c9cf-11eb-8fa0-dfbae543d1d3.png)

**Comment by AlexKirilov** [comment]
I found the solution...
![image](https://user-images.githubusercontent.com/5669746/121504603-0b9faf00-c9da-11eb-9116-fd39f2a6fd8b.png)
![image](https://user-images.githubusercontent.com/5669746/121504630-10fcf980-c9da-11eb-9136-638f81d9cbe3.png)

**Comment by jginsburgn** [comment]
Thanks for sharing the knowledge of how to solve :)
