### ISSUE TITLE
Error Output is Unicode Encoded and Doesn't Respect New Lines

### ISSUE THREAD

**Issue by johnnyshankman** [karma-runner/karma#3293]
### Expected behaviour

When I (or my team) insert a syntax error into my tests, karma reports the error with a stack trace that is legible.

### Actual behaviour

When I (or my team) insert a syntax error into my tests, karma reports the error with a stack trace that is unicode encoded and does not respect new lines, making it illegible.

### Environment Details

- Karma version (output of `karma --version`): 3.1.4
  - Also using `webpack` 4.27.1, and `webpack-karma` 2.0.0
  - Changing versions of `webpack-karma` doesn't seem to solve anything
- Relevant part of your `karma.config.js` file

I've removed all complex parts in order to isolate what is causing the issue. Here is my bare minimum karma config which still produces the issue.
```
{
    basePath: '',
    browsers: ['ChromeHeadless', 'FirefoxHeadless'],
    captureTimeout: 60000,
    colors: true,
    frameworks: [],
    files: [
      'spec/unit/spec_index.js'
    ],
    port: 9876,
    preprocessors: {
      'spec/unit/spec_index.js': ['webpack', 'sourcemap']
    },
    webpack: webpackConfig,
    webpackServer: {
      quiet: false
    }
  }
```

### Steps to reproduce the behaviour

Insert a syntax error within the `beforeEach()` of any test.
Get encoded output such as:
```
  {
    "message": "Uncaught ReferenceError: beforeEach is not defined\nat spec/unit/spec_index.js:95055:3\n\nReferenceError: beforeEach is not defined\n    at _default (spec/unit/spec_index.js:95055:3)\n    at Object.<anonymous> (spec/unit/spec_index.js:231:34)\n    at __webpack_require__ (spec/unit/spec_index.js:64:30)\n    at spec/unit/spec_index.js:197:18\n    at spec/unit/spec_index.js:200:10",
    "str": "Uncaught ReferenceError: beforeEach is not defined\nat spec/unit/spec_index.js:95055:3\n\nReferenceError: beforeEach is not defined\n    at _default (spec/unit/spec_index.js:95055:3)\n    at Object.<anonymous> (spec/unit/spec_index.js:231:34)\n    at __webpack_require__ (spec/unit/spec_index.js:64:30)\n    at spec/unit/spec_index.js:197:18\n    at spec/unit/spec_index.js:200:10"
  }
```

A much more intense example I've run into:

```
{
    "message": "Uncaught Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):\nSyntaxError: /Users/john/Documents/workspace/company/project/spec/unit/amp/components/amp_container_spec.js: Unexpected token, expected \";\" (31:23)\n\n\u001b[0m \u001b[90m 29 | \u001b[39m      }\u001b[0m\n\u001b[0m \u001b[90m 30 | \u001b[39m    }\u001b[33m;\u001b[39m\u001b[0m\n\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 31 | \u001b[39m    welcome\u001b[33m.\u001b[39mto\u001b[33m.\u001b[39msyntax()errrrrr\u001b[33m;\u001b[39m\u001b[33m;\u001b[39m\u001b[33m;\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m    | \u001b[39m                       \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 32 | \u001b[39m  })\u001b[33m;\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 33 | \u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 34 | \u001b[39m  it(\u001b[32m'wraps the body in the IntlProvider'\u001b[39m\u001b[33m,\u001b[39m \u001b[36mfunction\u001b[39m() {\u001b[0m\n    at Object.raise (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:3834:17)\n    at Object.unexpected (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:5142:16)\n    at Object.semicolon (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:5130:40)\n    at Object.parseExpressionStatement (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:7726:10)\n    at Object.parseExpressionStatement (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:2003:18)\n    at Object.parseStatementContent (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:7326:19)\n    at Object.parseStatement (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:7199:17)\n    at Object.parseStatement (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:1976:26)\n    at Object.parseBlockOrModuleBlockBody (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:7757:25)\n    at Object.parseBlockBody (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:7744:10)\n    at Object.parseBlock (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:7733:10)\n    at Object.parseFunctionBody (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:6865:24)\n    at forwardNoArrowParamsConversionAt (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:1954:70)\n    at Object.forwardNoArrowParamsConversionAt (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:2148:16)\n    at Object.parseFunctionBody (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:1954:19)\n    at Object.parseArrowExpression (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:6818:10)\nat spec/unit/spec_index.js:104174:1\n\nError: Module build failed (from ./node_modules/babel-loader/lib/index.js):\nSyntaxError: /Users/john/Documents/workspace/company/project/spec/unit/amp/components/amp_container_spec.js: Unexpected token, expected \";\" (31:23)\n\n\u001b[0m \u001b[90m 29 | \u001b[39m      }\u001b[0m\n\u001b[0m \u001b[90m 30 | \u001b[39m    }\u001b[33m;\u001b[39m\u001b[0m\n\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 31 | \u001b[39m    welcome\u001b[33m.\u001b[39mto\u001b[33m.\u001b[39msyntax()errrrrr\u001b[33m;\u001b[39m\u001b[33m;\u001b[39m\u001b[33m;\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m    | \u001b[39m                       \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 32 | \u001b[39m  })\u001b[33m;\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 33 | \u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 34 | \u001b[39m  it(\u001b[32m'wraps the body in the IntlProvider'\u001b[39m\u001b[33m,\u001b[39m \u001b[36mfunction\u001b[39m() {\u001b[0m\n    at Object.raise (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:3834:17)\n    at Object.unexpected (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:5142:16)\n    at Object.semicolon (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:5130:40)\n    at Object.parseExpressionStatement (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:7726:10)\n    at Object.parseExpressionStatement (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:2003:18)\n    at Object.parseStatementContent (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:7326:19)\n    at Object.parseStatement (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:7199:17)\n    at Object.parseStatement (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:1976:26)\n    at Object.parseBlockOrModuleBlockBody (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:7757:25)\n    at Object.parseBlockBody (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:7744:10)\n    at Object.parseBlock (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:7733:10)\n    at Object.parseFunctionBody (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:6865:24)\n    at forwardNoArrowParamsConversionAt (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:1954:70)\n    at Object.forwardNoArrowParamsConversionAt (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:2148:16)\n    at Object.parseFunctionBody (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:1954:19)\n    at Object.parseArrowExpression (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:6818:10)\n    at Object.<anonymous> (spec/unit/spec_index.js:104174:7)\n    at __webpack_require__ (webpack:///webpack/bootstrap:63 <- spec/unit/spec_index.js:64:30)\n    at webpackContext (webpack:///spec/unit%20sync%20_spec$:361 <- spec/unit/spec_index.js:99804:9)\n    at Array.forEach (<anonymous>)\n    at Object.<anonymous> (webpack:///spec/unit/spec_index.js:19 <- spec/unit/spec_index.js:236:21)\n    at __webpack_require__ (webpack:///webpack/bootstrap:63 <- spec/unit/spec_index.js:64:30)\n    at webpack:///webpack/bootstrap:196 <- spec/unit/spec_index.js:197:18\n    at spec/unit/spec_index.js:200:10",
    "str": "Uncaught Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):\nSyntaxError: /Users/john/Documents/workspace/company/project/spec/unit/amp/components/amp_container_spec.js: Unexpected token, expected \";\" (31:23)\n\n\u001b[0m \u001b[90m 29 | \u001b[39m      }\u001b[0m\n\u001b[0m \u001b[90m 30 | \u001b[39m    }\u001b[33m;\u001b[39m\u001b[0m\n\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 31 | \u001b[39m    welcome\u001b[33m.\u001b[39mto\u001b[33m.\u001b[39msyntax()errrrrr\u001b[33m;\u001b[39m\u001b[33m;\u001b[39m\u001b[33m;\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m    | \u001b[39m                       \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 32 | \u001b[39m  })\u001b[33m;\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 33 | \u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 34 | \u001b[39m  it(\u001b[32m'wraps the body in the IntlProvider'\u001b[39m\u001b[33m,\u001b[39m \u001b[36mfunction\u001b[39m() {\u001b[0m\n    at Object.raise (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:3834:17)\n    at Object.unexpected (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:5142:16)\n    at Object.semicolon (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:5130:40)\n    at Object.parseExpressionStatement (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:7726:10)\n    at Object.parseExpressionStatement (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:2003:18)\n    at Object.parseStatementContent (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:7326:19)\n    at Object.parseStatement (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:7199:17)\n    at Object.parseStatement (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:1976:26)\n    at Object.parseBlockOrModuleBlockBody (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:7757:25)\n    at Object.parseBlockBody (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:7744:10)\n    at Object.parseBlock (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:7733:10)\n    at Object.parseFunctionBody (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:6865:24)\n    at forwardNoArrowParamsConversionAt (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:1954:70)\n    at Object.forwardNoArrowParamsConversionAt (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:2148:16)\n    at Object.parseFunctionBody (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:1954:19)\n    at Object.parseArrowExpression (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:6818:10)\nat spec/unit/spec_index.js:104174:1\n\nError: Module build failed (from ./node_modules/babel-loader/lib/index.js):\nSyntaxError: /Users/john/Documents/workspace/company/project/spec/unit/amp/components/amp_container_spec.js: Unexpected token, expected \";\" (31:23)\n\n\u001b[0m \u001b[90m 29 | \u001b[39m      }\u001b[0m\n\u001b[0m \u001b[90m 30 | \u001b[39m    }\u001b[33m;\u001b[39m\u001b[0m\n\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 31 | \u001b[39m    welcome\u001b[33m.\u001b[39mto\u001b[33m.\u001b[39msyntax()errrrrr\u001b[33m;\u001b[39m\u001b[33m;\u001b[39m\u001b[33m;\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m    | \u001b[39m                       \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 32 | \u001b[39m  })\u001b[33m;\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 33 | \u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 34 | \u001b[39m  it(\u001b[32m'wraps the body in the IntlProvider'\u001b[39m\u001b[33m,\u001b[39m \u001b[36mfunction\u001b[39m() {\u001b[0m\n    at Object.raise (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:3834:17)\n    at Object.unexpected (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:5142:16)\n    at Object.semicolon (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:5130:40)\n    at Object.parseExpressionStatement (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:7726:10)\n    at Object.parseExpressionStatement (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:2003:18)\n    at Object.parseStatementContent (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:7326:19)\n    at Object.parseStatement (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:7199:17)\n    at Object.parseStatement (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:1976:26)\n    at Object.parseBlockOrModuleBlockBody (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:7757:25)\n    at Object.parseBlockBody (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:7744:10)\n    at Object.parseBlock (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:7733:10)\n    at Object.parseFunctionBody (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:6865:24)\n    at forwardNoArrowParamsConversionAt (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:1954:70)\n    at Object.forwardNoArrowParamsConversionAt (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:2148:16)\n    at Object.parseFunctionBody (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:1954:19)\n    at Object.parseArrowExpression (/Users/john/Documents/workspace/company/project/node_modules/@babel/parser/lib/index.js:6818:10)\n    at Object.<anonymous> (spec/unit/spec_index.js:104174:7)\n    at __webpack_require__ (webpack:///webpack/bootstrap:63 <- spec/unit/spec_index.js:64:30)\n    at webpackContext (webpack:///spec/unit%20sync%20_spec$:361 <- spec/unit/spec_index.js:99804:9)\n    at Array.forEach (<anonymous>)\n    at Object.<anonymous> (webpack:///spec/unit/spec_index.js:19 <- spec/unit/spec_index.js:236:21)\n    at __webpack_require__ (webpack:///webpack/bootstrap:63 <- spec/unit/spec_index.js:64:30)\n    at webpack:///webpack/bootstrap:196 <- spec/unit/spec_index.js:197:18\n    at spec/unit/spec_index.js:200:10"
  }
```
You can see just from the code blocks that new lines aren't happening and my whole trace is on one unicode filled line.

I've attempted to hack my own `formatError` function to unencode everything, but even then although the output is unencoded the `\n`s are still are there. Something adds back in a slew of `\n`s into the output even though I've explicitly removed them.

```
  formatError: function(error) {
      var x = error;
      var r = /\\u([\d\w]{4})/gi;
      x = x.replace(/\n/g, "") // Remove '\n'
      x = x.replace(r, function (match, grp) {
        return String.fromCharCode(parseInt(grp, 16)); // Unencode unicode
      });

      return x;
    }
```

Any idea what could be causing such an odd issue?

**Comment by johnjbarton** [comment]
I'm unsure where (how) you are seeing this output.  The 'reporter' plugins are responsible for formatting error messages and I don't see any in your config. 

The first output is just a toString() rendering of the object created by karma client:
https://github.com/karma-runner/karma/blob/master/client/karma.js#L146
As such it looks correct, it has newline characters embedded because it has multiple lines in the string.

The second output has encoded unicode characters, I guess because that is what is in the source files...
