### ISSUE TITLE
Text string with emoji crashes the karma-server

### ISSUE THREAD

**Issue by fetis** [karma-runner/karma#3323]
This bug is triggered by the next Jasmine test

```javascript
it('should accept emoji', () => {
  expect('😀').toBe('1');
});
```
### Expected behaviour
Print fail output and contine running

### Actual behaviour
Prints fail output and crashes with error
`ERROR [karma-server]: Error: Invalid character (�) in string: Expected '😀' to be '1'.`

### Environment Details

Karma version: 4.1.0

### Full stack trace
```
ERROR [karma-server]: Error: Invalid character (�) in string: Expected '😀' to be '1'.
    at UserContext.&lt;anonymous&gt; (src/app/category-admin/services/category-admin.service.spec.ts:234:20)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:391:1)
    at ProxyZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/zone-testing.js:289:1)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:390:1)
 at index 10
    at XMLStringifier.module.exports.XMLStringifier.assertLegalChar (/Users/sergeyf/job/case-management-frontend/node_modules/karma-junit-reporter/node_modules/xmlbuilder/lib/XMLStringifier.js:153:15)
    at XMLStringifier.assertLegalChar (/Users/sergeyf/job/case-management-frontend/node_modules/karma-junit-reporter/node_modules/xmlbuilder/lib/XMLStringifier.js:4:59)
    at XMLStringifier.module.exports.XMLStringifier.eleText (/Users/sergeyf/job/case-management-frontend/node_modules/karma-junit-reporter/node_modules/xmlbuilder/lib/XMLStringifier.js:33:19)
    at new XMLText (/Users/sergeyf/job/case-management-frontend/node_modules/karma-junit-reporter/node_modules/xmlbuilder/lib/XMLText.js:17:35)
    at XMLElement.module.exports.XMLNode.text (/Users/sergeyf/job/case-management-frontend/node_modules/karma-junit-reporter/node_modules/xmlbuilder/lib/XMLNode.js:165:15)
    at XMLElement.module.exports.XMLNode.node (/Users/sergeyf/job/case-management-frontend/node_modules/karma-junit-reporter/node_modules/xmlbuilder/lib/XMLNode.js:157:15)
    at XMLElement.module.exports.XMLNode.element (/Users/sergeyf/job/case-management-frontend/node_modules/karma-junit-reporter/node_modules/xmlbuilder/lib/XMLNode.js:102:28)
    at XMLElement.module.exports.XMLNode.ele (/Users/sergeyf/job/case-management-frontend/node_modules/karma-junit-reporter/node_modules/xmlbuilder/lib/XMLNode.js:357:19)
    at /Users/sergeyf/job/case-management-frontend/node_modules/karma-junit-reporter/index.js:165:14
    at Array.forEach (<anonymous>)
    at JUnitReporter.specSuccess.specSkipped.specFailure (/Users/sergeyf/job/case-management-frontend/node_modules/karma-junit-reporter/index.js:164:18)
    at JUnitReporter.BaseReporter.onSpecComplete (/Users/sergeyf/job/case-management-frontend/node_modules/karma/lib/reporters/base.js:109:12)
    at Server.<anonymous> (/Users/sergeyf/job/case-management-frontend/node_modules/karma/lib/events.js:40:26)
    at emitTwo (events.js:131:20)
    at Server.emit (events.js:214:7)
    at Browser.onResult (/Users/sergeyf/job/case-management-frontend/node_modules/karma/lib/browser.js:164:20)
    at Socket.socket.on (/Users/sergeyf/job/case-management-frontend/node_modules/karma/lib/browser.js:214:42)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at /Users/sergeyf/job/case-management-frontend/node_modules/socket.io/lib/socket.js:528:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by johnjbarton** [comment]
Well I have no idea how this call stack can happen.  From the bottom up to 

> at XMLStringifier.module.exports.XMLStringifier.assertLegalChar (/Users/sergeyf/job/case-management-frontend/node_modules/karma-junit-reporter/node_modules/xmlbuilder/lib/XMLStringifier.js:153:15)

is fine: the karma-junit-reporter is failing to correctly handle the emoji in an error message.  How zonejs can get involved is beyond me.

In any case, this is on karma-junit-reporter, not something karma-runner can fix.

**Comment by fetis** [comment]
@johnjbarton thanks for the clarification, I'll move it to karma-junit-reporter
