### ISSUE TITLE
Cant run Karma

### ISSUE THREAD

**Issue by garciaErick** [karma-runner/karma#3336]
### Expected behaviour
karma start
### Actual behaviour
karma start
#/usr/lib/node_modules/karma/lib/server.js:118
  async start () {
        ^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/karma/lib/cli.js:8:16)
### Environment Details
Latest karma version 
I just installed and I get this error and I cannot seem to finish installation

**Comment by johnjbarton** [comment]
Your version of nodejs is out of date. Please reinstall and try again.
