### ISSUE TITLE
Browser log, that should be printed inside tests, printed before all tests

### ISSUE THREAD

**Issue by ilgonmic** [karma-runner/karma#3373]
### Expected behaviour
Every log in browser should be in border of related test
E.g. (https://github.com/ilgonmic/karma-ts-test )
```
HeadlessChrome 77.0.3844 (Mac OS X 10.14.6)  MyTest foo FAILED
        Error: foo
            at MyTest.foo (test.js:25:9)
            at Context.<anonymous> (test.js:31:20)

// for passed test
ERROR: 'MY FAIL'
LOG: 'MY LOG
LOG ON NEXT LINE'

//for failed test
ERROR: 'MY FAIL'
LOG: 'MY LOG
LOG ON NEXT LINE'
HeadlessChrome 77.0.3844 (Mac OS X 10.14.6) org.my ServiceTest valueFailTest FAILED
        Error: valueFailTest
            at ServiceTest.valueFailTest (test.js:16:51)
            at Context.<anonymous> (test.js:43:25)


HeadlessChrome 77.0.3844 (Mac OS X 10.14.6) org.my ServiceTest valueFailTest2 FAILED
        Error: valueFailTest2
            at ServiceTest.valueFailTest2 (test.js:20:51)
            at Context.<anonymous> (test.js:47:25)
HeadlessChrome 77.0.3844 (Mac OS X 10.14.6): Executed 4 of 4 (3 FAILED) (0.006 secs / 0 secs)
```
### Actual behaviour
All logs printed before test reporting
```
ERROR: 'MY FAIL'
LOG: 'MY LOG
LOG ON NEXT LINE'
ERROR: 'MY FAIL'
LOG: 'MY LOG
LOG ON NEXT LINE'
ERROR: 'MY FAIL'
LOG: 'MY LOG
LOG ON NEXT LINE'
HeadlessChrome 77.0.3844 (Mac OS X 10.14.6)  MyTest foo FAILED
        Error: foo
            at MyTest.foo (test.js:25:9)
            at Context.<anonymous> (test.js:31:20)
HeadlessChrome 77.0.3844 (Mac OS X 10.14.6) org.my ServiceTest valueFailTest FAILED
        Error: valueFailTest
            at ServiceTest.valueFailTest (test.js:16:51)
            at Context.<anonymous> (test.js:43:25)
HeadlessChrome 77.0.3844 (Mac OS X 10.14.6) org.my ServiceTest valueFailTest2 FAILED
        Error: valueFailTest2
            at ServiceTest.valueFailTest2 (test.js:20:51)
            at Context.<anonymous> (test.js:47:25)
HeadlessChrome 77.0.3844 (Mac OS X 10.14.6): Executed 4 of 4 (3 FAILED) (0.006 secs / 0 secs)
TOTAL: 3 FAILED, 1 SUCCESS
```
### Environment Details

- Karma version (output of `karma --version`):
Karma version: 4.3.0
- Relevant part of your `karma.config.js` file
```
  config.set({
    "singleRun": true,
    "autoWatch": false,
    "files": [
      "/Users/ilya.goncharov/repos/karma-ts-test/test.js"
    ],
    "frameworks": [
      "mocha"
    ],
    "browsers": [
      "ChromeHeadless"
    ]
  });
```
### Steps to reproduce the behaviour

1. Small sample (https://github.com/ilgonmic/karma-ts-test) with only karma and mocha framework
2. Test with `console.log` in body
3. `node_modules/.bin/karma start`

Is there known problem? And is there some workaround for it?

**Comment by johnjbarton** [comment]
The test logs are printed as they happen, during the test.  The test results are printed by the reporter you select.  So to have them integrated you need to change/rewrite the reporter.

**Comment by ilgonmic** [comment]
@johnjbarton So, it is expected behaviour for default 'progress' reporter, am I right?

**Comment by johnjbarton** [comment]
Yes that's my experience. Unfortunately all of the reporters I've seen seem to follow that pattern.

**Comment by ilgonmic** [comment]
Just for history
It can be solved via `window.__karma__.result` property
It should be patched in 'client' side (via framework or directly in test code) like this
```
const resultFn = window.__karma__.result
window.__karma__.result = function(result) {
    console.log(`TEST_ENDED\n${JSON.stringify(result)}`
    resultFn(result)
}
```
And then it should be catched on reporter side vid `onBrowserLog` message
In reporter, we can collect information of logs and associate it with tests
