### ISSUE TITLE
karama test initial route defaulting to nil rather than "/"

### ISSUE THREAD

**Issue by zendevil** [karma-runner/karma#3538]
I'm running tests in my app using the following:

```
karma start --single-run
```
But I get the result:
```
05 07 2020 02:50:46.438:WARN [proxy]: proxy "target" normalized to "target/"
05 07 2020 02:50:46.545:INFO [karma-server]: Karma v5.1.0 server started at http://0.0.0.0:9876/
05 07 2020 02:50:46.546:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
05 07 2020 02:50:46.552:INFO [launcher]: Starting browser ChromeHeadless
05 07 2020 02:50:47.236:INFO [Chrome Headless 83.0.4103.116 (Mac OS 10.15.5)]: Connected on socket MnIh7bNkshwzTvOVAAAA with id 2452405
Chrome Headless 83.0.4103.116 (Mac OS 10.15.5) WARN: 're-frame: overwriting', ':sub', 'handler for:', {ns: null, name: 'display-products', fqn: 'display-products', _hash: 1721830266, cljs$lang$protocol_mask$partition0$: 2153775105, cljs$lang$protocol_mask$partition1$: 4096}

Chrome Headless 83.0.4103.116 (Mac OS 10.15.5) WARN: 're-frame: overwriting', ':sub', 'handler for:', {ns: null, name: 'filters', fqn: 'filters', _hash: 974726919, cljs$lang$protocol_mask$partition0$: 2153775105, cljs$lang$protocol_mask$partition1$: 4096}

Chrome Headless 83.0.4103.116 (Mac OS 10.15.5) INFO: 'Installing %c%s%c and enabling features %c%s %c%s %c%s%c%s', 'color:black;font-weight:bold;', 'CLJS DevTools 1.0.0', 'color:black', 'color:#0000ff', ':formatters', 'color:#ccc', ':hints', 'color:#ccc', ':async', 'color:transparent', 

Chrome Headless 83.0.4103.116 (Mac OS 10.15.5) WARN: 'Feature :formatters cannot be installed. Unsupported Javascript context: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/83.0.4103.116 Safari/537.36.'

Chrome Headless 83.0.4103.116 (Mac OS 10.15.5) LOG: '"navigating to " nil'

Chrome Headless 83.0.4103.116 (Mac OS 10.15.5) ERROR
 Uncaught Error: Target container is not a DOM element.
 at ci.js:131092:85

 Error: Target container is not a DOM element.
     at Object.exports.render (ci.js:131092:91)
     at Object.reagent$dom$render_comp [as render_comp] (ci.js:131122:48)
     at Function.cljs$core$IFn$_invoke$arity$3 (ci.js:131182:20)
     at Function.cljs$core$IFn$_invoke$arity$2 (ci.js:131170:27)
     at Object.vendo$core$mount_components [as mount_components] (ci.js:135479:27)
     at Object.vendo$core$init_BANG_ [as init_BANG_] (ci.js:135488:19)
     at ci.js:153675:12
```
Why is the route defaulting to nil and not "/"?

**Comment by johnjbarton** [comment]
The error message is from `ci.js` not from karma.
