### ISSUE TITLE
Karma test cases breaking in node 15.1

### ISSUE THREAD

**Issue by PPInfy** [karma-runner/karma#3571]
Hi Team,

I have node 15.1 and node 10.x. The same Karma with Angular 9 Tests work fine in node 10.x. But when it is used with node 15.1 we are getting the following error and the test breaks abruptly. There is no pattern other than the below error.

12 11 2020 12:19:28.046:ERROR [karma-server]: TypeError: Cannot read property 'range' of undefined
    at handleRangeHeaders (<MyProjectPath>\webpack-dev-middleware\lib\util.js:131:21)
    at processRequest (<MyProjectPath>\webpack-dev-middleware\lib\middleware.js:98:19)
    at ready (<MyProjectPath>\webpack-dev-middleware\lib\util.js:53:12)
    at handleRequest (<MyProjectPath>\webpack-dev-middleware\lib\util.js:182:5)
    at <MyProjectPath>\webpack-dev-middleware\lib\middleware.js:64:7
    at new Promise (<anonymous>)
    at middleware (<MyProjectPath>\webpack-dev-middleware\lib\middleware.js:63:12)
    at <MyProjectPath>\@angular-devkit\build-angular\src\angular-cli-files\plugins\karma.js:270:13
    at call (<MyProjectPath>\connect\index.js:239:7)
    at next (<MyProjectPath>\connect\index.js:183:5)
    at <MyProjectPath>\karma\lib\web-server.js:24:9
    at call (<MyProjectPath>\connect\index.js:239:7)
    at next (<MyProjectPath>\connect\index.js:183:5)
    at nullProxy (<MyProjectPath>\karma\lib\middleware\proxy.js:80:52)
    at call (<MyProjectPath>\connect\index.js:239:7)
    at next (<MyProjectPath>\connect\index.js:183:5)

**Comment by ekdev2** [comment]
Our issues are related I think.
https://github.com/karma-runner/karma/issues/3570

**Comment by PPInfy** [comment]
Ya maybe @ekdev2 . But our tickets have a different error trace.

**Comment by Glassig** [comment]
I use node 15.2.0, and karma 5.2.3, and I also get this error. It showed up recently.

**Comment by Glassig** [comment]
Downgrading node to v 14.15.1 works

**Comment by johnjbarton** [comment]
We only support LTS versions.  Also the call stack points to webpack.  Maybe add some logging to narrow down the issue.

**Comment by thomasturrell** [comment]
@johnjbarton I see the same error on node 14.15.2.

**Comment by yktoo** [comment]
Amazing, a minor Node update that broke all tests.

For those running Debian/Ubuntu, I've fixed that by uninstalling `nodejs`, downloading [nodejs_14.15.1-deb-1nodesource1_amd64.deb](https://deb.nodesource.com/node_14.x/pool/main/n/nodejs/nodejs_14.15.1-deb-1nodesource1_amd64.deb) from [nodesource pool](https://deb.nodesource.com/node_14.x/pool/main/n/nodejs/) and installing it with `sudo dpkg -i ...`.

**Comment by johnjbarton** [comment]
If you have a problem on node v14, please open a issue.  This issue is about v15 which we do not support.

**Comment by sachin1989solanki** [comment]
Hi @johnjbarton I am facing same problem with node v14.15.2.
17 12 2020 07:18:56.924:ERROR [karma-server]: TypeError: Cannot read property 'range' of undefined
Its working fine with our previous node v14.15.1.

Please provide us solution as soon possible.

**Comment by Mayur123-mg** [comment]
> Hi @johnjbarton I am facing same problem with node v14.15.2.
> 17 12 2020 07:18:56.924:ERROR [karma-server]: TypeError: Cannot read property 'range' of undefined
> Its working fine with our previous node v14.15.1.
> 
> Please provide us solution as soon possible.

i also get same issue docker pipeline get error in ng test command

**Comment by johnjbarton** [comment]
Please do not comment on this bug unless your comment is about node 15.  We don't support v15 so we don't plan to reopen this bug.

If you have a problem with v14, please open an issue.

There is a bug in node v14.15.2 that impacts webpack, #3588

**Comment by nvahalik** [comment]
Node v14 isn't supported on Apple Silicon.
Therefore, you cannot (currently) run karma on Apple Silicon machines.

**Comment by AllForNothing** [comment]
@nvahalik I'm using an M1 mac book,  and it works for me! Thanks!!

**Comment by rp1192kr** [comment]
I am getting below error while running npm run test:
26 07 2022 14:02:53.542:ERROR [karma-server]: UnhandledRejection
Cannot read properties of undefined (reading 'success')
TypeError: Cannot read properties of undefined (reading 'success')
    at TestCommand.runSingleTarget (C:\Users\ttc2563\ngpp-clustering-ui\node_modules\@angular\cli\models\packages\angular\cli\models\architect-command.ts:242:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at TestCommand.runArchitectTarget (C:\Users\ttc2563\ngpp-clustering-ui\node_modules\@angular\cli\models\packages\angular\cli\models\architect-command.ts:263:16)
    at TestCommand.validateAndRun (C:\Users\ttc2563\ngpp-clustering-ui\node_modules\@angular\cli\models\packages\angular\cli\models\command.ts:163:14)
    at Object.runCommand (C:\Users\ttc2563\ngpp-clustering-ui\node_modules\@angular\cli\models\packages\angular\cli\models\command-runner.ts:189:12)
    at default_1 (C:\Users\ttc2563\ngpp-clustering-ui\node_modules\@angular\cli\lib\cli\packages\angular\cli\lib\cli\index.ts:32:27)
