### ISSUE TITLE
Error KARMA-SERVER

### ISSUE THREAD

**Issue by Pximena** [karma-runner/karma#3580]
/ Generating browser application bundles (phase: building)...27 11 2020 17:54:32.245:WARN [karma]: No captured browser, open http://localhost:9876/
27 11 2020 17:54:32.256:INFO [karma-server]: Karma v5.1.1 server started at http://localhost:9876/
27 11 2020 17:54:32.258:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
27 11 2020 17:54:32.289:INFO [launcher]: Starting browser Chrome
27 11 2020 17:54:32.446:ERROR [karma-server]: UncaughtException:: spawn UNKNOWN
27 11 2020 17:54:32.448:ERROR [karma-server]: Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:403:11)
    at spawn (node:child_process:573:9)
    at spawnWithoutOutput (C:\Users\ACER\pruebas-angular\node_modules\karma\lib\launchers\process.js:169:26)
    at Object.ProcessLauncher._execCommand (C:\Users\ACER\pruebas-angular\node_modules\karma\lib\launchers\process.js:75:21)
    at Object.ProcessLauncher._start (C:\Users\ACER\pruebas-angular\node_modules\karma\lib\launchers\process.js:33:10)
    at Object.<anonymous> (C:\Users\ACER\pruebas-angular\node_modules\karma\lib\launchers\process.js:19:10)
    at Object.emit (node:events:388:22)
    at Object.BaseLauncher.start (C:\Users\ACER\pruebas-angular\node_modules\karma\lib\launchers\base.js:52:10)
    at Object.j (C:\Users\ACER\pruebas-angular\node_modules\karma\lib\launcher.js:108:17)
    at Object.setTimeout.bind.j (C:\Users\ACER\pruebas-angular\node_modules\qjobs\qjobs.js:143:18)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7) {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawn'
}

**Comment by johnjbarton** [comment]
Looks like an issue with karma-chrome-launcher.
