### ISSUE TITLE
Cannot import .mjs from .ts "Cannot find module '@angular/platform-browser/animations'"

### ISSUE THREAD

**Issue by satanTime** [karma-runner/karma#3736]
Hi all,

unfortunately, I failed to find a solution myself and need your help.

The thing is when I upgrade to angular 13, which uses `.mjs` instead of `.js`, my `.ts` files cannot import libraries and fail.

```
Error: Cannot find module '@angular/platform-browser/animations' from '/Volumes/MGS/Projects/ng-mocks/libs/ng-mocks/src/lib/mock-module/create-resolvers.js'
    at /Volumes/MGS/Projects/ng-mocks/node_modules/karma-typescript/src/bundler/resolve/resolver.ts:224:27
    at /Volumes/MGS/Projects/ng-mocks/node_modules/browser-resolve/index.js:265:24
    at /Volumes/MGS/Projects/ng-mocks/node_modules/resolve/lib/async.js:117:17
    at processDirs (/Volumes/MGS/Projects/ng-mocks/node_modules/resolve/lib/async.js:268:39)
    at isdir (/Volumes/MGS/Projects/ng-mocks/node_modules/resolve/lib/async.js:275:32)
    at /Volumes/MGS/Projects/ng-mocks/node_modules/resolve/lib/async.js:25:69
    at FSReqCallback.oncomplete (node:fs:198:21)
infrastructure_error Error: Unable to resolve module [@angular/platform-browser/animations] from [/Volumes/MGS/Projects/ng-mocks/libs/ng-mocks/src/lib/mock-module/create-resolvers.js]
{
  "basedir": "/Volumes/MGS/Projects/ng-mocks",
  "extensions": [
    ".js",
    ".json",
    ".mjs",
    ".ts",
    ".tsx"
  ],
  "moduleDirectory": [
    "node_modules"
  ],
  "modules": {
    "assert": "/Volumes/MGS/Projects/ng-mocks/node_modules/assert/build/assert.js",
    "buffer": "/Volumes/MGS/Projects/ng-mocks/node_modules/buffer/index.js",
    "child_process": "/Volumes/MGS/Projects/ng-mocks/node_modules/karma-typescript/dist/bundler/resolve/empty.js",
    "cluster": "/Volumes/MGS/Projects/ng-mocks/node_modules/karma-typescript/dist/bundler/resolve/empty.js",
    "console": "/Volumes/MGS/Projects/ng-mocks/node_modules/console-browserify/index.js",
    "constants": "/Volumes/MGS/Projects/ng-mocks/node_modules/constants-browserify/constants.json",
    "crypto": "/Volumes/MGS/Projects/ng-mocks/node_modules/crypto-browserify/index.js",
    "dgram": "/Volumes/MGS/Projects/ng-mocks/node_modules/karma-typescript/dist/bundler/resolve/empty.js",
    "dns": "/Volumes/MGS/Projects/ng-mocks/node_modules/karma-typescript/dist/bundler/resolve/empty.js",
    "domain": "/Volumes/MGS/Projects/ng-mocks/node_modules/domain-browser/source/index.js",
    "events": "/Volumes/MGS/Projects/ng-mocks/node_modules/events/events.js",
    "fs": "/Volumes/MGS/Projects/ng-mocks/node_modules/karma-typescript/dist/bundler/resolve/empty.js",
    "http": "/Volumes/MGS/Projects/ng-mocks/node_modules/stream-http/index.js",
    "https": "/Volumes/MGS/Projects/ng-mocks/node_modules/https-browserify/index.js",
    "module": "/Volumes/MGS/Projects/ng-mocks/node_modules/karma-typescript/dist/bundler/resolve/empty.js",
    "net": "/Volumes/MGS/Projects/ng-mocks/node_modules/karma-typescript/dist/bundler/resolve/empty.js",
    "os": "/Volumes/MGS/Projects/ng-mocks/node_modules/os-browserify/browser.js",
    "path": "/Volumes/MGS/Projects/ng-mocks/node_modules/path-browserify/index.js",
    "punycode": "/Volumes/MGS/Projects/ng-mocks/node_modules/punycode/punycode.js",
    "querystring": "/Volumes/MGS/Projects/ng-mocks/node_modules/querystring-es3/index.js",
    "readline": "/Volumes/MGS/Projects/ng-mocks/node_modules/karma-typescript/dist/bundler/resolve/empty.js",
    "repl": "/Volumes/MGS/Projects/ng-mocks/node_modules/karma-typescript/dist/bundler/resolve/empty.js",
    "stream": "/Volumes/MGS/Projects/ng-mocks/node_modules/stream-browserify/index.js",
    "_stream_duplex": "/Volumes/MGS/Projects/ng-mocks/node_modules/karma-typescript/node_modules/readable-stream/lib/_stream_duplex.js",
    "_stream_passthrough": "/Volumes/MGS/Projects/ng-mocks/node_modules/karma-typescript/node_modules/readable-stream/lib/_stream_passthrough.js",
    "_stream_readable": "/Volumes/MGS/Projects/ng-mocks/node_modules/karma-typescript/node_modules/readable-stream/lib/_stream_readable.js",
    "_stream_transform": "/Volumes/MGS/Projects/ng-mocks/node_modules/karma-typescript/node_modules/readable-stream/lib/_stream_transform.js",
    "_stream_writable": "/Volumes/MGS/Projects/ng-mocks/node_modules/karma-typescript/node_modules/readable-stream/lib/_stream_writable.js",
    "string_decoder": "/Volumes/MGS/Projects/ng-mocks/node_modules/karma-typescript/node_modules/string_decoder/lib/string_decoder.js",
    "sys": "/Volumes/MGS/Projects/ng-mocks/node_modules/util/util.js",
    "timers": "/Volumes/MGS/Projects/ng-mocks/node_modules/timers-browserify/main.js",
    "tls": "/Volumes/MGS/Projects/ng-mocks/node_modules/karma-typescript/dist/bundler/resolve/empty.js",
    "tty": "/Volumes/MGS/Projects/ng-mocks/node_modules/tty-browserify/index.js",
    "url": "/Volumes/MGS/Projects/ng-mocks/node_modules/url/url.js",
    "util": "/Volumes/MGS/Projects/ng-mocks/node_modules/util/util.js",
    "vm": "/Volumes/MGS/Projects/ng-mocks/node_modules/vm-browserify/index.js",
    "zlib": "/Volumes/MGS/Projects/ng-mocks/node_modules/browserify-zlib/lib/index.js",
    "_process": "/Volumes/MGS/Projects/ng-mocks/node_modules/process/browser.js"
  },
  "filename": "",
  "paths": []
}
```

This is the PR to upgrade to Angular 13: https://github.com/ike18t/ng-mocks/pull/1487
This is its CI/CD failing job: https://app.circleci.com/pipelines/github/ike18t/ng-mocks/2827/workflows/91b8e4a5-7bac-4ea6-84b6-7554eda5a00b/jobs/102013

This is the karma config: https://github.com/ike18t/ng-mocks/blob/master/karma.conf.ts

I've tried to add:

```
    files: [
      {
        pattern: '**/*.mjs',
        type: 'module',
        watched: false,
      },
      // ...
    ],
```

it slowed down bootstrap and it is still failing with the same error.

**Comment by devoto13** [comment]
I don't think what you have tried has a chance to work. `type=module` means that the file contains ESM module natively working in the browser, which is not the case with [APF 13](https://angular.io/guide/angular-package-format) which is designed for the bundlers. 

As far as I understand `karma-typescript` has a built-in bundler and it's that bundler, which fails to resolve the file. This is a separate plugin and you may have better luck asking help from [them](https://github.com/monounity/karma-typescript) as `karma` core does not support Angular natively. Another option is to use Angular CLI plugin for running library tests. I successfully do so in the library I maintain, but it's definitely not as flexible as your setup based on `karma-typescript`.

**Comment by satanTime** [comment]
Hi @devoto13, thanks for the info. I ended up that I need to configure ts to process .mjs files, it almost got working, but the issue was that browser-resolve didn't find processed files. This is where I'm currently. 

Also, thanks for the hint. I thought to check how angular 13 configures karma and to implement the same thing in mine.

**Comment by satanTime** [comment]
I moved to karma-webpack and it works well now.
