### ISSUE TITLE
Latest version of socket.io causes tests to fail on macOS

### ISSUE THREAD

**Issue by Chuckv01** [karma-runner/karma#3857]
Karma does not seem to be working properly with the latest version of [socket.io](https://github.com/socketio/socket.io) when running on macOS. Tests will always fail with the following output:

```
Chrome 115.0.0.0 (Mac OS 10.15.7) ERROR
  Some of your tests did a full page reload!
Chrome 115.0.0.0 (Mac OS 10.15.7) ERROR
  Some of your tests did a full page reload!
25 07 2023 13:08:13.224:ERROR [karma-server]: UncaughtException: TypeError: Cannot read properties of null (reading '57590020')
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    at Socket.emitUntyped (/node_modules/socket.io/dist/typed-events.js:69:22)
    at /Users/charles/Documents/pfizer/newton-app-dhm-demo-hybrid/node_modules/socket.io/dist/socket.js:703:39
```

Overriding the socket.io dependency version to `4.6.1` within `package.json` fixes the issue:

```
"overrides": {
  "socket.io": "4.6.1"
}
```

Suggest one of the following:

- Pinning socket.io to `4.6.1` [here](https://github.com/karma-runner/karma/blob/master/package.json#L450)
- Figuring out if karma needs to be updated to work with `socket.io@4.7.1`
- If not an issue in karma, filing a bug with socket.io

**Comment by sroucheray** [comment]
Saw the same problem on Firefox on an Angular 12 project with the conjunction of the new socket.io version and the `client.clearContext` configuration set to false. I had to fix the resolution of socket.io to `"socket.io": "~4.6.2"` in my project.
