### ISSUE TITLE
junit xml report does not show stack trace if it has more lines. It shows only the first line

### ISSUE THREAD

**Issue by dineshrb** [karma-runner/karma#482]
AssertionError: expected [ Array(0) ] not to be empty
	    at Assertion.<anonymous> (/Users/Home/web/workspace/build/testtool/test/vendor.js:598:14)
	    at Assertion.Object.defineProperty.get (/Users/Home/web/workspace/build/testtool/test/vendor.js:2826:33)
	    at Context.eval (test/controllers/payroll_controller_test:47:54)

Only the first line is displayed in the junit report. Other lines are required while integrating with jenkins.

**Comment by Dignifiedquire** [comment]
Closing due to inactivity. Please feel free to reopen a new issue with updated info if this is still a problem. Thanks.
