### ISSUE TITLE
Cannot start karma - no provider for jasmine

### ISSUE THREAD

**Issue by vanntastic** [karma-runner/karma#706]
Hey Guys:

I'm having an issue with getting karma running (on a non angularJS project) - I've installed all dependencies with npm and ran the karma init my.conf.js 2 times. When I try and run karma start my.conf.js, here's the output:

```
/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:9
  throw error('No provider for "' + name + '"!');
        ^
Error: No provider for "framework:jasmine"! (Resolving: framework:jasmine)
    at error (/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:22:68)
    at Object.parent.get     (/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:9:13)
at get (/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:54:19)
at /usr/local/lib/node_modules/karma/lib/server.js:27:14
at Array.forEach (native)
at start (/usr/local/lib/node_modules/karma/lib/server.js:26:21)
at invoke (/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:75:15)
at Object.exports.start (/usr/local/lib/node_modules/karma/lib/server.js:178:12)
at Object.<anonymous> (/usr/local/lib/node_modules/karma/bin/karma:19:39)
at Module._compile (module.js:449:26)
at Object.Module._extensions..js (module.js:467:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.runMain (module.js:492:10)
at process.startup.processNextTick.process._tickCallback (node.js:275:11)
```

I have karma-jasmine and karma-phantomjs-launcher in node_modules, is there something else that I'm doing wrong? What else can I check?

Thanks,
- Vann

**Comment by aleclarson** [comment]
I'm getting this error with Node v0.12.0 and v0.10.36

Does anyone know how I can fix this?

**Comment by maksimr** [comment]
@aleclarson can you post your `karma.config.js`

**Comment by aleclarson** [comment]
```
// karma.config.js

module.exports = function(config) {
	config.set({
		basePath: "",
		frameworks: ["jasmine"],
		plugins: [require("karma-webpack")],
		files: ["build/**/*.js"],
		exclude: ["node_modules"],
		preprocessors: {
			"build/**/*.js": ["webpack"]
		},
		reporters: ["progress"],
		port: 9876,
		colors: true,
		logLevel: config.LOG_DEBUG,
		autoWatch: true,
		browsers: ["Chrome"],
		singleRun: false
	});
};
```

**Comment by maksimr** [comment]
@aleclarson remove property `plugins`(then karma will by default load all plugins from node_modules by pattern `karma-*`) or add to it `karma-jasmine`.


```js
plugins: [require("karma-webpack"), require('karma-jasmine')],
```

**Comment by aleclarson** [comment]
@maksimr Oh I get it. Thanks!

**Comment by arunkumarg** [comment]
I faced same error and tried to resolve for couple of hours.

Finally I figured out the issue.  Which is "Karma module need to install LOCALLY not Globally"  But you can have Karma-cli module can be installed globally.

**Comment by liwonder** [comment]
@arunkumarg Thanks for your sharing! It really helpful!

**Comment by WeijianXu** [comment]
@arunkumarg Your methods are really helpful!
