### ISSUE TITLE
installing karma from the npm repository causes a 404

### ISSUE THREAD

**Issue by elachys** [karma-runner/karma#840]
```
$ npm install karma
npm http GET https://registry.npmjs.org/karma
npm http 200 https://registry.npmjs.org/karma
npm http GET https://registry.npmjs.org/karma/-/karma-0.10.6.tgz
npm http 404 https://registry.npmjs.org/karma/-/karma-0.10.6.tgz
npm ERR! fetch failed https://registry.npmjs.org/karma/-/karma-0.10.6.tgz
npm ERR! Error: 404 Not Found
npm ERR!     at WriteStream.<anonymous> (/usr/local/Cellar/node/0.10.18/lib/node_modules/npm/lib/utils/fetch.js:57:12)
npm ERR!     at WriteStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at fs.js:1596:14
npm ERR!     at /usr/local/Cellar/node/0.10.18/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:103:5
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.0.0
npm ERR! command "/usr/local/Cellar/node/0.10.18/bin/node" "/usr/local/bin/npm" "install" "karma"
npm ERR! cwd /Users/XXXX
npm ERR! node -v v0.10.18
npm ERR! npm -v 1.3.8
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/XXXX/npm-debug.log
npm ERR! not ok code 0
```

**Comment by dm89** [comment]
I am having this issue now. Any suggestions?
