### ISSUE TITLE
Allow source maps for non-preprocessed files

### ISSUE THREAD

**Issue by vojtajina** [karma-runner/karma#893]
Based on discussion in #594.

We could add `sourceMap` attr to file patterns, `true`.
Also a default preprocessor might check for in-lined source map.

**Comment by tschaub** [comment]
I put together a [`source-map-support` plugin](https://www.npmjs.com/package/karma-source-map-support) that improves stack traces in Chrome with inline source maps (like those produced from Browserify with the `debug` option).

Here's a comparison of a stack without/with this plugin.

```diff
--- stack-without	2015-01-02 15:02:55.000000000 -0700
+++ stack-with	2015-01-02 15:03:12.000000000 -0700
@@ -1,11 +1,11 @@
 AssertionError: case 2: expected [ 0, 0.6666666666666666 ] to deeply equal [ 0, 0.5 ]
-    at Function.assert.deepEqual (http://localhost:9876/absolute/var/folders/6m/3grlt52x7w3047wy0n6j7dr00000gn/T/2d4c510ad9122153a42db199d1cc8e9553208184.browserify:1848:32)
-    at Context.<anonymous> (http://localhost:9876/absolute/var/folders/6m/3grlt52x7w3047wy0n6j7dr00000gn/T/2d4c510ad9122153a42db199d1cc8e9553208184.browserify:6061:14)
+    at Function.assert.deepEqual (node_modules/chai/lib/chai/interface/assert.js:205:1)
+    at Context.<anonymous> (src/scenes/util/geom.test.js:27:1)
     at callFn (http://localhost:9876/base/node_modules/mocha/mocha.js:4496:21)
     at Test.Runnable.run (http://localhost:9876/base/node_modules/mocha/mocha.js:4489:7)
     at Runner.runTest (http://localhost:9876/base/node_modules/mocha/mocha.js:4892:10)
     at http://localhost:9876/base/node_modules/mocha/mocha.js:4970:12
     at next (http://localhost:9876/base/node_modules/mocha/mocha.js:4817:14)
     at http://localhost:9876/base/node_modules/mocha/mocha.js:4827:7
     at next (http://localhost:9876/base/node_modules/mocha/mocha.js:4766:23)
     at http://localhost:9876/base/node_modules/mocha/mocha.js:4794:5
```

The plugin simply delegates to the [`source-map-support` package](https://www.npmjs.com/package/source-map-support).

Things are still less than ideal.  The debugger doesn't generate clickable links for compiled sources.  I'll see if there's a way to address this.

Not sure if this will work for other cases, but it is working well for me when using [`karma-browserify`](https://www.npmjs.com/package/karma-browserify) to generate bundles before tests run.
