### ISSUE TITLE
Extraneous error with fsevents and recursive-readdir could break karma-coverage

### ISSUE THREAD

**Issue by MindCookin** [karma-runner/karma#975]
Hello

I'm having a problem trying to get karma-coverage (v0.2.1) running with the last version of karma(0.12.1): 
```bash
[gulp] Using gulpfile /Users/medianet/Documents/Work/bbva/wizzo_front_experiments/gulpfile.js
[gulp] Starting 'test'...
[gulp] Finished 'test' after 3.03 ms
INFO [karma]: Karma v0.12.1 server started at http://localhost:9123/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.7 (Mac OS X)]: Connected on socket dSKtK0fzmd_P7wgcpXOW with id 98803585
PhantomJS 1.9.7 (Mac OS X) ERROR
  TypeError: 'undefined' is not an object (evaluating '__cov_w5iXYxo9oGaxixd5zUvm3A.s['2']')
  at /Users/medianet/Documents/Work/bbva/wizzo_front_experiments/app/js/components/common/contact-picker-service.js:9
[ ... previous line get repeated for each test  ... ]
PhantomJS 1.9.7 (Mac OS X): Executed 0 of 0 ERROR (0.19 secs / 0 secs)
ERROR [karma]: [TypeError: Cannot call method 'att' of undefined]
TypeError: Cannot call method 'att' of undefined
    at onBrowserComplete (/Users/medianet/Documents/Work/bbva/wizzo_front_experiments/node_modules/karma-junit-reporter/index.js:50:11)
    at null.<anonymous> (/Users/medianet/Documents/Work/bbva/wizzo_front_experiments/node_modules/karma/lib/events.js:15:22)
    at EventEmitter.emit (events.js:117:20)
    at onComplete (/Users/medianet/Documents/Work/bbva/wizzo_front_experiments/node_modules/karma/lib/browser.js:145:13)
    at Socket.<anonymous> (/Users/medianet/Documents/Work/bbva/wizzo_front_experiments/node_modules/karma/lib/events.js:15:22)
    at Socket.EventEmitter.emit [as $emit] (events.js:117:20)
    at SocketNamespace.handlePacket (/Users/medianet/Documents/Work/bbva/wizzo_front_experiments/node_modules/karma/node_modules/socket.io/lib/namespace.js:335:22)
    at Manager.onClientMessage (/Users/medianet/Documents/Work/bbva/wizzo_front_experiments/node_modules/karma/node_modules/socket.io/lib/manager.js:488:38)
    at WebSocket.Transport.onMessage (/Users/medianet/Documents/Work/bbva/wizzo_front_experiments/node_modules/karma/node_modules/socket.io/lib/transport.js:387:20)
    at Parser.<anonymous> (/Users/medianet/Documents/Work/bbva/wizzo_front_experiments/node_modules/karma/node_modules/socket.io/lib/transports/websocket/default.js:36:10)
```

The fact is that it seems to be a crossing issue (I have also reported into karma-coverage) but could be related with two karma dependencies: fsevents and recursive-readdir, because when I run "npm list" I get two errors: 

```bash
npm ERR! extraneous: fsevents@0.1.6 /Users/medianet/Documents/Work/bbva/wizzo_front_experiments/node_modules/karma/node_modules/chokidar/node_modules/fsevents
npm ERR! extraneous: recursive-readdir@0.0.2 /Users/medianet/Documents/Work/bbva/wizzo_front_experiments/node_modules/karma/node_modules/chokidar/node_modules/recursive-readdir
npm ERR! not ok code 0
```
I have karma installed locally, not globally. This problem started to happen when we update to karma 0.12.0.

Thanks in advance for any help around it. 

Greetings

Santi

**Comment by Dignifiedquire** [comment]
Closing due to inactivity
